### ISSUE TITLE
marytts server issue

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#648] opened 2016-11-27 10:47 UTC
hi,

i found the following error when try to run marytts server.

jayanta@jayantasPC:/local/mary/marytts/target/marytts-5.1.2/bin$ sudo ./marytts-server
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

MARY server 5.1.2 starting as a HTTP server...Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/icu/text/RuleBasedNumberFormat
	at marytts.language.fr.Preprocess.<init>(Preprocess.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:130)
	at marytts.modules.ModuleRegistry.instantiateModule(ModuleRegistry.java:87)
	at marytts.server.Mary.startModules(Mary.java:130)
	at marytts.server.Mary.startup(Mary.java:296)
	at marytts.server.Mary.startup(Mary.java:203)
	at marytts.server.Mary.main(Mary.java:513)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.RuleBasedNumberFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:385)
	at marytts.server.Mary$3.run(Mary.java:288)
jayanta@jayantasPC:/local/mary/marytts/target/marytts-5.1.2/bin$ 

Please Help

**Comment by psibre** [comment] 2016-11-27 10:55
Duplicate of #274, solved nearly two years ago.
Please update to a newer version.

**Closed by psibre** 2016-11-27 10:55 UTC
Labels: duplicate
