### ISSUE TITLE
How can I change the unit selector and concatenator?

### ISSUE THREAD

**Issue by Georgakopoulos** [marytts/marytts#291] opened 2015-03-17 13:05 UTC
I have created different voices based on one large Database.
Now I would like to be able to adjust dynamically (for each sentence) -preferred- or statically (for different voices) the choices regarding the number and/or the quality of units used by Mary's Selector/Concatenator.

My aim is to integrated in one way or the other a quality estimator to improve our speech synthesis.

Where can I influence these decisions and to what extend is that possible?

**Comment by Munzey** [comment] 2015-03-18 20:51
I'll try point you in the right direction and give you a brief rundown of how the unitselection process in mary works(deep breath):

Currently the marytts unit selection packages are found under the marytts runtime module (in later releases it will be all contained in its own module). `marytts.unitselection.UnitSelectionSynthesizer` contains the `synthesize` method which calls all the other multitude of classes in order for a target utterance to be synthesized. Its a good place to start if youd like to fully understand the process. 
In relation to your question, the `marytts.unitselection.select.UnitSelector` method `selectUnits()` is called which creates targets for each of the phones and boundaries in the target utterance and computes a target feature vector for each. The `marytts.unitselection.select.viterbi` algorithm is then applied. To quote the `Viterbi.apply()` javadoc:

>[it] carr[ies] out a Viterbi search for a prepared queue of ViterbiPoints[Constructor creates a queue of ViterbiPoints corresponding to the segments]. In a nutshell, each Point represents a target item (a target segment); for each target Point, a number of Candidate units in the voice database are determined; a Path structure is built up, based on local best transitions.

It then selects units by finding the best path and these are passed to the unit concatenator of the voice which concatenates them together into audio. 
So there ya have it. You could try limiting the candidate results returned for a target in the viterbi apply method. Or maybe try changing the concatenator used. Not sure if anything could be done dynamically. Maybe others have suggestions?

**Comment by Georgakopoulos** [comment] 2015-03-20 15:57
Thank you for your answer. I started looking into the methods and I hope I will understand at what point to interfere with the system. 

So just to confirm what I understood: 
If I change the java-code in some of the classes/methods you mentioned, every synthesis that my program is going to perform (indepent of which voice I will use) will be influenced by my changes?

And a quite early idea, but do you think I could work with a timeout in the Viterbi.apply() method to perform a quality estimation or would it disturb the runtime process?

**Comment by Munzey** [comment] 2015-03-20 16:58
To answer your questions:

>So just to confirm what I understood: 
If I change the java-code in some of the classes/methods you mentioned, every synthesis that my program is going to perform (indepent of which voice I will use) will be influenced by my changes?

Yes, so long as you recompile your changes and run a mary server instance from your edited mary system.

>And a quite early idea, but do you think I could work with a timeout in the Viterbi.apply() method to perform a quality estimation or would it disturb the runtime process?

You're going to need to elaborate more on this, not sure exactly what you mean

**Comment by Georgakopoulos** [comment] 2015-04-07 14:30
Thanks for that! 
As for the second part of my question: it was an early attempt to figure a way, to get the 10 best sentences of the Viterbi-Algorithm out of the program, but a timeout is not really going to help me with that. I will explain my solution as soon as its done for everyone who is interested.

I decided to use eclipse to work on the code to keep an overview over the classes and methods, but I can't seem to install the voices. The InstallerGUI works perfectly: copies the jar-files as it should, but my Server does not seem to recognize them. It only sees the voice-cmu-slt-hsmm but no other I installed!!! There have been similar problems, but I could not find a way to solve this one yet:
Does anybody know why???

**Comment by Georgakopoulos** [comment] 2015-04-08 13:39
I figured it out: I just had to Import the voice directory separately through eclipse, the installation of the marytts-installer was not enough.

Here is how it is done: MENU->FILE->IMPORT  choose EXISTING_MAVEN_PROJECTS browse to your created VOICE-Directory and click Ok. thats all!

**Comment by psibre** [comment] 2015-04-08 14:47
For the record, you need to add the voice to the Mary classpath in Eclipse. You can do this as you say,
* by importing the project as a Maven project, *or*
* by add the external voice jar file from wherever your voicebuilding happened (under `mary/voice-XYZ/target`), *and* if it's a unit-selection voice, setting the `mary.base` property to point to your voicebuilding directory's `mary` directory.

**Comment by Georgakopoulos** [comment] 2015-04-24 10:41
I am still working on  the same project I mentioned a few weeks ago. 
I am trying to create multiple audio based on a single Input:
--> So if I for example give the Input Text "Hello World" ,  MaryTTS will not create one output but several (In my case 10). I cant find the class in which I have to write a LOOP in order to do that and I am not sure if Mary will handle that without other problems (timeouts etc.)!?!?
If somebody can assist me with that I would be grateful and happy to share my results afterwards.

**Comment by Munzey** [comment] 2015-04-25 10:32
why not use the `marytts.LocalMaryInterface` in marytts-runtime and call `generateAudio(text)` with a loop? However if you did it this way you would need some way to access the parameters you are changing with each pass of the input.
Without knowing how you've changed the code its hard to give any more advice (if you push your branch to github I could maybe take a look). My only other suggestion would be to take a look at `marytts.server.Request.writeOutputData()` which is called at the end of every mary conversion.

**Comment by Georgakopoulos** [comment] 2015-04-28 10:49
That was what I was searching for. Now I am trying to figure out how to write the outputs to *separate files*. Do I have to change the **MaryData out** variable [in generateAudio(text)] in each loop? 

The parameters I am changing are pretty simple:  In **marytts.unitselection.select.viterbi** --> **findBestPath()** I am talking not only the **best = paths.get(0)** , but the other 9 paths as well and out of those I want to create additional wav. outputs.

**Comment by Munzey** [comment] 2015-04-28 13:34
unfortunately doing it the way you're suggesting without specific knowledge of how all this data gets passed around is going to cause you a major headache. Essentially you would need from the point where you begin to return *10 paths* (and if there were less or more than that you would of course need to handle this) to change all the methods affected by this to expect a list of lists. i.e a list of viterbi paths used to create a list of selected unit lists, then with each of these lists concatenate into an audio stream, add these to an audiostream list, have 'marytts.modules.Synthesis' handle a list of audio streams instead of one, which would then write this to MaryData's audio variable which would also need to be changed to a list of audio streams. You would then need to change the 'Request.writeOutputData()' method to suit your needs. 

On the other hand, you *could* do something like this instead:
```
LocalMaryInterface mary = new LocalMaryInterface();
for(int i = 0; i < 10; i++) {
  System.setProperty("viterbiPath.number", i.toString());
  AudioInputStream mary.generateAudio(someTextHere);
  //then write your audio stream to wherever
```

then of course you would need to modify the `Viterbi.findBestPath()` to use this property. You can use `marytts.server.MaryProperties.getProperty(String Property)` to retrieve the property.

**Comment by Georgakopoulos** [comment] 2015-04-28 13:59
Thanks a lot for your answer, you have been a great help already. I will work with your suggestion. I had thought about changing the passing of the data, but as you said it was going to be a huge effort and since I don't mind running the program several times it is going to to be a lot easier.

The things I have not understood yet: 
1. Where to implement your suggestion? Because if I do it in the **LocalMaryInterface** I don't seem to achieve anything (even with a breakpoint in the **generateAudio(String text)** it seems to never get to this method). I figured because it is an **SynthesisException** method. 
-I am pretty sure I'm missing sth. simple, but I don't know what.-

2. How do I write my audio stream? In what type do I have to write it to get an output and how could I change the name for example?

**Comment by Munzey** [comment] 2015-04-28 14:52
You could create a class in the marytts runtime module under one of the unitselection packages for consistency, import what you need and just write a main method containing the code I wrote above. 
As for writing an audio stream, [AudioSystem#write](http://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioSystem.html#write(javax.sound.sampled.AudioInputStream,%20javax.sound.sampled.AudioFileFormat.Type,%20java.io.File)) is what you're after. 
And regarding your question as to how to change the name of each file, I recommend you go learn java.

**Comment by Munzey** [comment] 2015-04-28 15:08
I forgot to mention you would also need to set the locale and voice for the LocalMaryInterface if you want it to use your voice data

**Comment by Georgakopoulos** [comment] 2015-04-28 15:20
Set the locale and voice after I created the new LocalMaryInterface() right?
I see that my questions have been a little frustrating for you. I am relatively a beginner with java, so I am missing some basics (e.g: AudioSystem#write). Thanks for your patience though and I do appreciate your help.

**Comment by Munzey** [comment] 2015-04-28 15:36
no worries, ill help out a little more; here is the code you should add to Viterbi.java after line 508:
```
ViterbiPath best;
		Integer pathNum = Integer.valueOf(MaryProperties.getProperty("viterbiPath.number"));
		//make sure there is indeed that many paths
		if (pathNum != null  && pathNum < paths.size()) {
			best = paths.get(pathNum);
		}//default to best path
		else {
			best = paths.get(0);
		}
```

**Comment by Munzey** [comment] 2015-04-28 15:52
and yes the test class should look something like this:

```
//all your imports go here

public class viterbiAnalysis{

    private LocalMaryInterface mary;
    
    public viterbiAnalysis(){
        mary = new LocalMaryInterface();
        mary.setLocale(yourlocale);
        mary.setVoice(yourVoiceName);
    }

    public static void main(string [] args){
        for(int i = 0; i < 10; i++) {
            System.setProperty("viterbiPath.number", i.toString());
            AudioInputStream is =  mary.generateAudio(someTextHere);
            File fileX = new File("path/to/the/file" + "_" + i + ".wav");
            AudioSystem.write(is, AudioFileFormat.Type.WAVE, fileX);
        }
    }
}
```
to run just make sure everything is on the classpath :)

**Closed** 2015-04-28 15:59 UTC
Labels: question, voicebuilding

**Comment by Georgakopoulos** [comment] 2015-04-30 09:21
That is great help and a lot to work with. Thank you...

**Comment by Georgakopoulos** [comment] 2015-05-11 14:16
It is working. Here are my methods.
**MAIN:**

´´´
package marytts.unitselection;
import some_imports;

public class MultipleAudio {
	
	private static LocalMaryInterface mary;
	
	public MultipleAudio(){
        try {
			mary = new LocalMaryInterface();
		} catch (MaryConfigurationException e) {
			e.printStackTrace();
		}
        mary.setLocale(Locale.GERMAN);
        mary.setVoice("VOICE_NAME"); 
        System.out.println("Konstruktor");
    }

	public static void main(String[] args) {
		new MultipleAudio();													//setzt Variablen des Konstruktors
		System.out.println("Anfang der MultipleAudio-Schleife");
		Integer i;
		for(i = 0; i < 100; i++) { 
			System.setProperty("viterbiPath.number", Integer.toString(i));   //Setzt den Integer als globale Property an
			AudioInputStream audio = null; 									//initialisiert audio
			try {
				audio = mary.generateAudio("Beliebiger Satz."); 			//Synthetisiert den Satz in der Klammer
			} catch (SynthesisException e) {
				e.printStackTrace();
			}
			File fileX = new File("/Some/Path/you/like/" + "Name" + i + ".wav"); 	//erzeugt ein File ("Datenpath" + mit_dem_Namen)
            try {
				AudioSystem.write(audio, AudioFileFormat.Type.WAVE, fileX); 	//schreibt Audio in fileX
				i = i + 19;														//um schlechtere Paths zu testen! (Bemerkung: auch for-Schleife muss geändert werden)
            } catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
}

´´´

**In Viterbi.java:**

´´´
Collections.sort(paths);

				ViterbiPath best;				
				Integer pathNum = Integer.valueOf(MaryProperties.getProperty("viterbiPath.number"));  //Gets value of viterbiPath.number and saves in pathnum
				System.out.println("pathNum =" + pathNum);
				//make sure there is indeed that many paths
					if (pathNum != null  && pathNum < paths.size()) { //Notice: if pathNum >= paths.size --> simply uses paths.get(0) NO NOTIFICATION OTHER THAN PRINTS
						best = paths.get(pathNum); 					//set the Path we want to create
						System.out.println("Anzahl Paths" + paths.size());
						System.out.println("pathNum =" + pathNum);
						System.out.println("Score of pathNum =" + best);
					}//default to best path
					else {
						best = paths.get(0);
					}
´´´

**Comment by psibre** [comment] 2015-05-11 14:22
Nice, thanks for sharing!

(also fixed the formatting in your post :grin:)

**Comment by Georgakopoulos** [comment] 2015-05-18 09:57
I managed to synthesize different paths, but they don't seem do differ a lot from one another.
After further looking into it, I found that the only paths I get are the possibilities for the last unit of each sentence ```List<ViterbiPath> paths = lastPoint.getPaths();``` and not for all the possibilities. As I understood it, it takes for each unit the best candidate and offers you in the end only the different candidates for the last unit, so all the other units before the last, are exactly the same.

**My aim:** To synthesize sentences that clearly differ from one another, by using different elements of the database and doing this not only for the last unit.

**Questions:** Is my understanding of how viterbi works, now correct?
What is a good way to get other paths beside the one mentioned above, that differ in quality?
How can I access them (maybe similar to ```List<ViterbiPath> paths = lastPoint.getPaths();```)?

**Comment by Munzey** [comment] 2015-05-18 16:34
you're on the right track but your understanding of the viterbi algorithm is a little off:
for each token in a sentence there is a list of viterbi candidates, as well as a dummy start and end token at the beginning and end of the sentence. A path between two tokens' candidates has a cost. For each candidate of a token, the cheapest path between it and one of the next token's candidates is decided. Between the dummy end token and final 'real' token of the sentence, the cheapest path can then easily be decided as each viterbiPath remembers the cheapest path that came before it, thus you have the best path after sorting the list of viterbi paths and calling `ViterbiPath best = paths.get(0);`

So the problem is that by calling `lastPoint.getPaths()`, you are really only seeing the paths between the candidates for the final token of the sentence and the 'end' dummy token. so although with your current implementation you are getting variation between which final path is being chosen, the next path back will select its 'best path' to one of the candidates of the previous token.
the issue is that this means theres a very high chance the paths will be very similar, even more so if your test sentence contains a low occurring word in your database. You would probably have more luck with words that were not recorded and possibly try using a much higher number of paths.
The current beam search limit is set to 100 but you could try raising the beamSize search value, or actually just turning it off setting its value to -1. This can be done by setting the property `voice.${VOICENAME}.viterbi.beamsize = 100`

Take for example the sentence, "I adore her". Theres probably a lot more occurrences of the word "her" in the database, compared to "adore" which maybe only occurs once. thus the "I adore" will always be the same as the cheapest costing path between the tokens would not change.

A feature enhancement we are looking at for the future will come in the form of a rather large refactoring of the code base, where unitselection will be its own module, allowing for easier access and modding of the config file etc.. We will also add a method to concatenate unique unit indices from the database, basically allowing one to hardcode unit IDs to be selected for concatenation :)

**Comment by Georgakopoulos** [comment] 2015-07-23 10:58
A little question on your last answer:
"*For each candidate of a token, the cheapest path between it and* **one of the next token's** *candidates is calculated.*" 
Based on what criteria does it choose what Candidate of the next token it is going to calculate? Or does it simply start with one and checks every other combination?

A related question for my understanding: 
Can anybody help me understand how the  **addpath()** Method in *Viterbi.java* works?
It seems to add paths to a List **paths** for the Candidates it has and then comparing them with **other paths** till it finds a list of best paths! 
Are these all the possible paths I mentioned in the first question? how are they being calculated?

**Comment by Munzey** [comment] 2015-07-23 11:05
> A little question on your last answer:
> "For each candidate of a token, the cheapest path between it and one of the next token's candidates is calculated."
> Based on what criteria does it choose what Candidate of the next token it is going to calculate? Or does it simply start with one and checks every other combination?

yes it checks every combination to find the cheapest path.

> A related question for my understanding:
> Can anybody help me understand how the addpath() Method in Viterbi.java works?
> It seems to add paths to a List paths for the Candidates it has and then comparing them with other paths till it finds a list of best paths!
> Are these all the possible paths I mentioned in the first question? how are they being calculated?

yes the best path is essentially a "path of paths". you should take a look at the source code and the different viterbi classes and their member variables, that should help you understand.

**Comment by Georgakopoulos** [comment] 2015-07-28 09:59
Thank you that helped! I need another little advice: 
I am trying to find a variable to catch the number/size of the units used in the sentence Mary is in. 
For example: "Hello." would have sth. like: *-h; h-E; E-l; l-l; l-O; O-;* (**6 targets**, for which it chooses Candidates and paths). This size of targets is what I try to get access to, so I can work with it.

**Comment by Georgakopoulos** [comment] 2015-07-28 12:01
I found a pretty easy solution by myself. Here it is:
I used an Iterator in the Constructor of the Viterbi-Class:
```java
for (Target target : targets) { //loop goes through all the targets of the list
			ViterbiPoint nextPoint = new ViterbiPoint(target);
			
			if (last != null) { // continue to build up the queue
				last.setNext(nextPoint);
			} else { // firstPoint is the start of the queue
				firstPoint = nextPoint;
				// dummy start path:
				firstPoint.getPaths().add(new ViterbiPath(null, null, 0));
			}
			last = nextPoint;
/**/			lengthTargets++;    //here I count the targets in the list. I created a global int variable lengthTargets
		}
```

**Comment by psibre** [comment] 2015-07-28 12:57
Why don't you just do `targets.size()`?

**Comment by Georgakopoulos** [comment] 2015-07-28 13:08
I thought that was the first thing I tried, but apparently I just got lost in the code. 
*targets.size()* works perfectly fine!
