### ISSUE TITLE
Total reliable=0 , feature maker exception

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#684] opened 2017-02-09 20:58 UTC
![3](https://cloud.githubusercontent.com/assets/9119099/22802873/5dc3feb0-ef34-11e6-89fc-b2e9c63b05ce.JPG)
Hi
 if some one knows how to fix it please let me know 
Thanks

**Comment by seblemaguer** [comment] 2017-02-10 06:24
duplicate of #683

**Closed by seblemaguer** 2017-02-10 06:24 UTC
Labels: duplicate
