### ISSUE TITLE
HMMVoiceMakeVoice Error

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#631] opened 2016-10-31 11:17 UTC
HI guys , I have a problem with **# HMMVoiceMakeVoice** ,i got  many times this problem i am confused so this is my **# error**  
```
Opening` GUI....... 
Loading database layout:
Reading config file /home/abdullahi/voice/data/SOMVOICE/database.config
Reading external binaries config file /home/abdullahi/voice/sources/marytts/lib/external/externalBinaries.config
Loading basename list from file /home/abdullahi/voice/data/SOMVOICE/basenames.lst
Found 65 files in basename list
Loading features from file /home/abdullahi/voice/data/SOMVOICE/mary/features.txt

Running: /usr/bin/perl /home/abdullahi/voice/data/SOMVOICE/hts/scripts/Training.pl /home/abdullahi/voice/data/SOMVOICE/hts/scripts/Config.pm

The training procedure can take several hours...
Detailed information about the training status can be found in the logfile:
  /home/abdullahi/voice/data/SOMVOICE/hts/log-2016.10.31-12:29:42

Training voice: my_voice
The following is general information about execution of training steps:

Step: Start preparing environments at Mon Oct 31 12:29:42 EAT 2016

Step: Start computing variance floors at Mon Oct 31 12:29:42 EAT 2016

Step: Start initialization & reestimation at Mon Oct 31 12:29:43 EAT 2016

Step: Start making a monophone mmf at Mon Oct 31 12:30:17 EAT 2016

Step: Start embedded reestimation (monophone) at Mon Oct 31 12:30:17 EAT 2016

Step: Start copying monophone mmf to fullcontext one at Mon Oct 31 12:42:58 EAT 2016

Step: Start embedded reestimation (fullcontext) at Mon Oct 31 12:43:00 EAT 2016

Step: Start tree-based context clustering at Mon Oct 31 12:45:39 EAT 2016

Step: Start embedded reestimation (clustered) at Mon Oct 31 12:49:43 EAT 2016

Step: Start untying the parameter sharing structure at Mon Oct 31 12:57:21 EAT 2016

Step: Start embedded reestimation (untied) at Mon Oct 31 12:57:21 EAT 2016

Step: Start tree-based context clustering at Mon Oct 31 12:59:04 EAT 2016

Step: Start embedded reestimation (re-clustered) at Mon Oct 31 13:04:28 EAT 2016

Step: Start forced alignment for no-silent GV at Mon Oct 31 13:11:56 EAT 2016

Step: Start making global variance at Mon Oct 31 14:02:37 EAT 2016
java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException:  computation failed on file [/home/abdullahi/voice/data/SOMVOICE/]!
Command line was: [/usr/bin/perl /home/abdullahi/voice/data/SOMVOICE/hts/scripts/Training.pl /home/abdullahi/voice/data/SOMVOICE/hts/scripts/Config.pm].
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:189)
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:127)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

**Comment by seblemaguer** [comment] 2016-11-01 11:38
Hello,

what is indicated in :  `/home/abdullahi/voice/data/SOMVOICE/hts/log-2016.10.31-12:29:42`

**Comment by baaslaawe** [comment] 2016-11-01 13:37
thank you bro @seblemaguer  

[log-2016.10.31-12:29:42.txt](https://github.com/marytts/marytts/files/564136/log-2016.10.31-12.29.42.txt)

**Comment by baaslaawe** [comment] 2016-11-02 21:56
help me please

**Comment by psibre** [comment] 2016-11-03 05:53
Looks like a duplicate of #245 to me.

**Comment by baaslaawe** [comment] 2016-11-03 06:57
i was read this #245 try to change this line

$beam       = '1500 100 5000'; 
to something like that

$beam       = '2000 500 20000'; 

still i have problem help me @psibre

**Comment by seblemaguer** [comment] 2016-11-03 07:26
This is more an HTS problem than a MaryTTS problem. Look at the files with this kind of behaviour : 

```
 Processing Data: SOM00042.cmp ; Label SOM00042.lab
 WARNING [-9999]  HSMMAlign: No tokens survived to final node of network at beam 20000
```

In this case, you reached the beam limit. Therefore, go to the line before and you have the inpacted label (here: SOM00042.lab). Either your discard this file from the corpus (easy but effective solution) either you try to see what is going wrong. In both cases, it is up to you now.

**Comment by baaslaawe** [comment] 2016-11-03 08:15
so you meaning i will remove that file ,but must of file i got like this message ( WARNING [-9999]  HSMMAlign: No tokens survived to final node of network at beam ) so if i remove there no more corpus ,is there any other way to solution

**Comment by seblemaguer** [comment] 2016-11-03 08:20
no I mean the one with the exact line : ``` WARNING [-9999]  HSMMAlign: No tokens survived to final node of network at beam 20000```

20000 is your maximum beam size. Therefore, if you reach it it means it doesn't fine alignment.

**Comment by baaslaawe** [comment] 2016-11-03 08:31
ok thank you i will try

**Closed** 2016-11-21 20:33 UTC
Labels: duplicate, voicebuilding

**Comment by sravani40** [comment] 2021-03-22 09:43
TR 0
 Adjusting trace level

TR 3
 Adjusting trace level

// construct decision trees
TB 0.00 gv_str_ {*.state[2].stream[3]}
 Tree based clustering based on MDL criterion, threshold=2.102346e+01

 TB: Stats 67->1 [1.5%]  { 67->1 [1.5%] total }

TR 1
 Adjusting trace level

// output constructed trees
ST /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/str.inf
 Writing current questions/trees to file

Saving new HMM files ...
Edit Complete

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
#                 MINDUR                         5
#                 MAXSTDDEVCOEF                 10
#                 APPLYDURVARFLOOR              TRUE
#                 DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
                  NATURALWRITEORDER              TRUE
                  NATURALREADORDER              TRUE
                  APPLYVFLOOR                 TRUE

/voice/soft/hts/bin/HERest -A -C /home/sravani/Desktop/sravs1/hts/configs/trn.cnf -D -T 1 -S /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/gv.scp -I /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/gv.mlf -m 1 -H /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/clustered.mmf -M /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1 /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/gv.list 

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
#                 MINDUR                         5
#                 MAXSTDDEVCOEF                 10
#                 APPLYDURVARFLOOR              TRUE
#                 DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
#                 NATURALWRITEORDER              TRUE
#                 NATURALREADORDER              TRUE
#                 APPLYVFLOOR                 TRUE

HMM:
HERest  ML Updating: Transitions Means Variances 
 System is SHARED
67 Logical/67 Physical Models Loaded, VecSize=41
1 MMF input files

Pruning-Off

 Processing Data: arctic_a0003.cmp; Label arctic_a0003.lab
 Utterance prob per frame = 1.646101e+02
 Processing Data: arctic_a0006.cmp; Label arctic_a0006.lab
 Utterance prob per frame = 1.613500e+02
 Processing Data: arctic_a0007.cmp; Label arctic_a0007.lab
 Utterance prob per frame = 1.634129e+02
 Processing Data: arctic_a0009.cmp; Label arctic_a0009.lab
 Utterance prob per frame = 1.680770e+02
 Processing Data: arctic_a0010.cmp; Label arctic_a0010.lab
 Utterance prob per frame = 1.577086e+02
 Processing Data: arctic_a0011.cmp; Label arctic_a0011.lab
 Utterance prob per frame = 1.647520e+02
 Processing Data: arctic_a0012.cmp; Label arctic_a0012.lab
 Utterance prob per frame = 1.600084e+02
 Processing Data: arctic_a0013.cmp; Label arctic_a0013.lab
 Utterance prob per frame = 1.682582e+02
 Processing Data: arctic_a0014.cmp; Label arctic_a0014.lab
 Utterance prob per frame = 1.677634e+02
 Processing Data: arctic_a0016.cmp; Label arctic_a0016.lab
 Utterance prob per frame = 1.641726e+02
 Processing Data: arctic_a0018.cmp; Label arctic_a0018.lab
 Utterance prob per frame = 1.530151e+02
 Processing Data: arctic_a0019.cmp; Label arctic_a0019.lab
 Utterance prob per frame = 1.682357e+02
 Processing Data: arctic_a0020.cmp; Label arctic_a0020.lab
 Utterance prob per frame = 1.524024e+02
 Processing Data: arctic_a0021.cmp; Label arctic_a0021.lab
 Utterance prob per frame = 1.753805e+02
 Processing Data: arctic_a0022.cmp; Label arctic_a0022.lab
 Utterance prob per frame = 1.708585e+02
 Processing Data: arctic_a0024.cmp; Label arctic_a0024.lab
 Utterance prob per frame = 1.705458e+02
 Processing Data: arctic_a0025.cmp; Label arctic_a0025.lab
 Utterance prob per frame = 1.607201e+02
 Processing Data: arctic_a0026.cmp; Label arctic_a0026.lab
 Utterance prob per frame = 1.580308e+02
 Processing Data: arctic_a0027.cmp; Label arctic_a0027.lab
 Utterance prob per frame = 1.708108e+02
 Processing Data: arctic_a0028.cmp; Label arctic_a0028.lab
 Utterance prob per frame = 1.437234e+02
 Processing Data: arctic_a0029.cmp; Label arctic_a0029.lab
 Utterance prob per frame = 1.728652e+02
 Processing Data: arctic_a0030.cmp; Label arctic_a0030.lab
 Utterance prob per frame = 1.324728e+02
 Processing Data: arctic_a0031.cmp; Label arctic_a0031.lab
 Utterance prob per frame = 1.540683e+02
 Processing Data: arctic_a0032.cmp; Label arctic_a0032.lab
 Utterance prob per frame = 1.626406e+02
 Processing Data: arctic_a0033.cmp; Label arctic_a0033.lab
 Utterance prob per frame = 1.659836e+02
 Processing Data: arctic_a0034.cmp; Label arctic_a0034.lab
 Utterance prob per frame = 1.680705e+02
 Processing Data: arctic_a0036.cmp; Label arctic_a0036.lab
 Utterance prob per frame = 1.565002e+02
 Processing Data: arctic_a0039.cmp; Label arctic_a0039.lab
 Utterance prob per frame = 1.712634e+02
 Processing Data: arctic_a0040.cmp; Label arctic_a0040.lab
 Utterance prob per frame = 1.497315e+02
 Processing Data: arctic_a0043.cmp; Label arctic_a0043.lab
 Utterance prob per frame = 1.571729e+02
 Processing Data: arctic_a0044.cmp; Label arctic_a0044.lab
 Utterance prob per frame = 1.601922e+02
 Processing Data: arctic_a0045.cmp; Label arctic_a0045.lab
 Utterance prob per frame = 1.449808e+02
 Processing Data: arctic_a0049.cmp; Label arctic_a0049.lab
 Utterance prob per frame = 1.598006e+02
 Processing Data: arctic_a0050.cmp; Label arctic_a0050.lab
 Utterance prob per frame = 1.629775e+02
 Processing Data: arctic_a0051.cmp; Label arctic_a0051.lab
 Utterance prob per frame = 1.704949e+02
 Processing Data: arctic_a0052.cmp; Label arctic_a0052.lab
 Utterance prob per frame = 1.457398e+02
 Processing Data: arctic_a0053.cmp; Label arctic_a0053.lab
 Utterance prob per frame = 1.664662e+02
 Processing Data: arctic_a0055.cmp; Label arctic_a0055.lab
 Utterance prob per frame = 1.654767e+02
 Processing Data: arctic_a0056.cmp; Label arctic_a0056.lab
 Utterance prob per frame = 1.654692e+02
 Processing Data: arctic_a0059.cmp; Label arctic_a0059.lab
 Utterance prob per frame = 1.646025e+02
 Processing Data: arctic_a0061.cmp; Label arctic_a0061.lab
 Utterance prob per frame = 1.605541e+02
 Processing Data: arctic_a0063.cmp; Label arctic_a0063.lab
 Utterance prob per frame = 1.660332e+02
 Processing Data: arctic_a0064.cmp; Label arctic_a0064.lab
 Utterance prob per frame = 1.726035e+02
 Processing Data: arctic_a0065.cmp; Label arctic_a0065.lab
 Utterance prob per frame = 1.661660e+02
 Processing Data: arctic_a0066.cmp; Label arctic_a0066.lab
 Utterance prob per frame = 1.412271e+02
 Processing Data: arctic_a0067.cmp; Label arctic_a0067.lab
 Utterance prob per frame = 1.466958e+02
 Processing Data: arctic_a0068.cmp; Label arctic_a0068.lab
 Utterance prob per frame = 1.628413e+02
 Processing Data: arctic_a0070.cmp; Label arctic_a0070.lab
 Utterance prob per frame = 1.663277e+02
 Processing Data: arctic_a0072.cmp; Label arctic_a0072.lab
 Utterance prob per frame = 1.358155e+02
 Processing Data: arctic_a0074.cmp; Label arctic_a0074.lab
 Utterance prob per frame = 1.612902e+02
 Processing Data: arctic_a0078.cmp; Label arctic_a0078.lab
 Utterance prob per frame = 1.656713e+02
 Processing Data: arctic_a0082.cmp; Label arctic_a0082.lab
 Utterance prob per frame = 1.553253e+02
 Processing Data: arctic_a0083.cmp; Label arctic_a0083.lab
 Utterance prob per frame = 1.664682e+02
 Processing Data: arctic_a0084.cmp; Label arctic_a0084.lab
 Utterance prob per frame = 1.731068e+02
 Processing Data: arctic_a0085.cmp; Label arctic_a0085.lab
 Utterance prob per frame = 1.654372e+02
 Processing Data: arctic_a0086.cmp; Label arctic_a0086.lab
 Utterance prob per frame = 1.631044e+02
 Processing Data: arctic_a0087.cmp; Label arctic_a0087.lab
 Utterance prob per frame = 1.725119e+02
 Processing Data: arctic_a0090.cmp; Label arctic_a0090.lab
 Utterance prob per frame = 1.686786e+02
 Processing Data: arctic_a0091.cmp; Label arctic_a0091.lab
 Utterance prob per frame = 1.679639e+02
 Processing Data: arctic_a0092.cmp; Label arctic_a0092.lab
 Utterance prob per frame = 1.583057e+02
 Processing Data: arctic_a0093.cmp; Label arctic_a0093.lab
 Utterance prob per frame = 1.592646e+02
 Processing Data: arctic_a0094.cmp; Label arctic_a0094.lab
 Utterance prob per frame = 1.646362e+02
 Processing Data: arctic_a0095.cmp; Label arctic_a0095.lab
 Utterance prob per frame = 1.699962e+02
 Processing Data: arctic_a0096.cmp; Label arctic_a0096.lab
 Utterance prob per frame = 1.649738e+02
 Processing Data: arctic_a0097.cmp; Label arctic_a0097.lab
 Utterance prob per frame = 1.716555e+02
 Processing Data: arctic_a0098.cmp; Label arctic_a0098.lab
 Utterance prob per frame = 1.323378e+02
 Processing Data: arctic_a0100.cmp; Label arctic_a0100.lab
 Utterance prob per frame = 1.615227e+02
Total 2 floored variance elements in 2 different mixes
Saving hmm's to dir /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1
Reestimation complete - average log prob per frame = 1.615122e+02
     - total frames seen          = 6.700000e+01

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
                  MINDUR                         5
                  MAXSTDDEVCOEF                 10
                  APPLYDURVARFLOOR              TRUE
                  DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
                  NATURALWRITEORDER              TRUE
                  NATURALREADORDER              TRUE
                  APPLYVFLOOR                 TRUE


=========================================================================
Start making unseen models (GV) at Monday 22 March 2021 02:35:44 PM IST
=========================================================================

/voice/soft/hts/bin/HHEd -A -C /home/sravani/Desktop/sravs1/hts/configs/trn.cnf -D -T 1 -p -i -H /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/clustered.mmf -w /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/clustered_all.mmf /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/mku.hed /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/gv.list 

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
#                 MINDUR                         5
#                 MAXSTDDEVCOEF                 10
#                 APPLYDURVARFLOOR              TRUE
#                 DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
#                 NATURALWRITEORDER              TRUE
#                 NATURALREADORDER              TRUE
#                 APPLYVFLOOR                 TRUE

HHEd
 67/67 Models Loaded [3 states max, 1 mixes max]

TR 2
 Adjusting trace level

// load trees for mgc
LT /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/mgc.inf
 Loading questions/trees from file

// load trees for lf0
LT /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/lf0.inf
 Loading questions/trees from file

// load trees for str
LT /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/str.inf
 Loading questions/trees from file

// make unseen model
AU /home/sravani/Desktop/sravs1/hts/data/lists/full_all.list
 Creating HMMset using trees to add unseen triphones
 AU: 3410 Log/3410 Phys created from 67 Log/67 Phys

// make model compact
CO /home/sravani/Desktop/sravs1/hts/gv/qst001/ver1/tiedlist
 Create compact HMMList
 CO: HMMs 3410 Logical 3410 Physical

Saving new HMM files ...
Edit Complete

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
#                 MINDUR                         5
#                 MAXSTDDEVCOEF                 10
#                 APPLYDURVARFLOOR              TRUE
#                 DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
                  NATURALWRITEORDER              TRUE
                  NATURALREADORDER              TRUE
                  APPLYVFLOOR                 TRUE


==========================================================================================
Start making unseen models (speaker independent) at Monday 22 March 2021 02:35:45 PM IST
==========================================================================================

/voice/soft/hts/bin/HHEd -A -C /home/sravani/Desktop/sravs1/
