### ISSUE TITLE
Feature maker issues ;Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module PronunciationModel: Problem processing the data.

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#683] opened 2017-02-09 19:55 UTC
Got these errors in feature maker running even after doing every thing all over again 
![1](https://cloud.githubusercontent.com/assets/9119099/22800525/77bdb08a-ef2b-11e6-82f5-a1f66d5a0b32.JPG)
![2](https://cloud.githubusercontent.com/assets/9119099/22800539/7e50dba2-ef2b-11e6-8380-7aeeb70bad06.JPG)
![3](https://cloud.githubusercontent.com/assets/9119099/22800540/7e56d106-ef2b-11e6-8609-e8e2a29e200e.JPG)
Please help ,Don't know why i am getting these

**Comment by seblemaguer** [comment] 2017-02-10 10:12
this issue is a duplicate of #681. You didn't solve the problem as the locale ur_PK is not known (according to the second screenshot). Please keep the discussion on issue. Spawning issues makes everything more complicated to follow.

**Closed by seblemaguer** 2017-02-10 10:12 UTC
