### ISSUE TITLE
Can't run Voice Compiler ( API incompability org.codehaus.gmaven)

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#378] opened 2015-08-10 09:45 UTC
Hi folks,

I tried installing/compiling a voice (no HMM):

```
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
maven out>[INFO] Scanning for projects...
maven out>[INFO]                                                                         
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Building voice-cld.15084 5.2-SNAPSHOT
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] 
maven out>[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java-7-or-higher) @ voice-cld.15084 ---
maven out>[INFO] 
maven out>[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ voice-cld.15084 ---
maven out>[INFO] Executing: /bin/sh -c cd /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084 && git rev-parse --verify HEAD
maven out>[INFO] Working directory: /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084
maven out>[INFO] Storing buildNumber: null at timestamp: 1439199297921
maven out>[WARNING] Cannot get the branch information from the git repository: 
maven out>Detecting the current branch failed: fatal: Not a git repository (or any of the parent directories): .git
maven out>
maven out>[INFO] Executing: /bin/sh -c cd /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084 && git rev-parse --verify HEAD
maven out>[INFO] Working directory: /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084
maven out>[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ voice-cld.15084 ---
maven out>[debug] execute contextualize
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] Copying 9 resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ voice-cld.15084 ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ voice-cld.15084 ---
maven out>[debug] execute contextualize
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] skip non existing resourceDirectory /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084/src/test/resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ voice-cld.15084 ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ voice-cld.15084 ---
maven out>[INFO] 
maven out>[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ voice-cld.15084 ---
maven out>[INFO] Building jar: /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084/target/voice-cld.15084-5.2-SNAPSHOT.jar
maven out>[INFO] 
maven out>[INFO] --- maven-assembly-plugin:2.5.5:single (make-assembly) @ voice-cld.15084 ---
maven out>[INFO] Reading assembly descriptor: src/main/descriptors/installable.xml
maven out>[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /
maven out>[INFO] Building zip: /mnt/data/marytts_new/voices/cld/20150804/mary/voice-cld.15084/target/voice-cld.15084-5.2-SNAPSHOT.zip
maven out>[INFO] 
maven out>[INFO] --- gmaven-plugin:1.4:execute (default) @ voice-cld.15084 ---
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] BUILD FAILURE
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Total time: 01:29 min
maven out>[INFO] Finished at: 2015-08-10T11:36:26+02:00
maven out>[INFO] Final Memory: 20M/720M
maven out>[INFO] ------------------------------------------------------------------------
maven out>[ERROR] Failed to execute goal org.codehaus.gmaven:gmaven-plugin:1.4:execute (default) on project voice-cld.15084: Execution default of goal org.codehaus.gmaven:gmaven-plugin:1.4:execute failed: An API incompatibility was encountered while executing org.codehaus.gmaven:gmaven-plugin:1.4:execute: java.lang.NoSuchMethodError: org.codehaus.groovy.ast.ModuleNode.getStarImports()Ljava/util/List;
maven out>[ERROR] -----------------------------------------------------
maven out>[ERROR] realm =    plugin>org.codehaus.gmaven:gmaven-plugin:1.4
maven out>[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
maven out>[ERROR] urls[0] = file:/root/.m2/repository/org/codehaus/gmaven/gmaven-plugin/1.4/gmaven-plugin-1.4.jar
maven out>[ERROR] urls[1] = file:/root/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.4/gmaven-runtime-api-1.4.jar
maven out>[ERROR] urls[2] = file:/root/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-api/1.4/gmaven-feature-api-1.4.jar
maven out>[ERROR] urls[3] = file:/root/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-loader/1.4/gmaven-runtime-loader-1.4.jar
maven out>[ERROR] urls[4] = file:/root/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-support/1.4/gmaven-feature-support-1.4.jar
maven out>[ERROR] urls[5] = file:/root/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.4/gmaven-runtime-support-1.4.jar
maven out>[ERROR] urls[6] = file:/root/.m2/repository/org/sonatype/gshell/gshell-io/2.4/gshell-io-2.4.jar
maven out>[ERROR] urls[7] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
maven out>[ERROR] urls[8] = file:/root/.m2/repository/com/thoughtworks/qdox/qdox/1.12/qdox-1.12.jar
maven out>[ERROR] urls[9] = file:/root/.m2/repository/org/apache/maven/shared/file-management/1.2.1/file-management-1.2.1.jar
maven out>[ERROR] urls[10] = file:/root/.m2/repository/org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar
maven out>[ERROR] urls[11] = file:/root/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
maven out>[ERROR] urls[12] = file:/root/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
maven out>[ERROR] urls[13] = file:/root/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
maven out>[ERROR] urls[14] = file:/root/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
maven out>[ERROR] urls[15] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.0.4.1/maven-reporting-impl-2.0.4.1.jar
maven out>[ERROR] urls[16] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar
maven out>[ERROR] urls[17] = file:/root/.m2/repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
maven out>[ERROR] urls[18] = file:/root/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
maven out>[ERROR] urls[19] = file:/root/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
maven out>[ERROR] urls[20] = file:/root/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
maven out>[ERROR] urls[21] = file:/root/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
maven out>[ERROR] urls[22] = file:/root/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
maven out>[ERROR] urls[23] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-core/1.0-alpha-10/doxia-core-1.0-alpha-10.jar
maven out>[ERROR] urls[24] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
maven out>[ERROR] urls[25] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0.4/maven-reporting-api-2.0.4.jar
maven out>[ERROR] urls[26] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.0-alpha-10/doxia-site-renderer-1.0-alpha-10.jar
maven out>[ERROR] urls[27] = file:/root/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
maven out>[ERROR] urls[28] = file:/root/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.7/plexus-velocity-1.1.7.jar
maven out>[ERROR] urls[29] = file:/root/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
maven out>[ERROR] urls[30] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.0-alpha-10/doxia-decoration-model-1.0-alpha-10.jar
maven out>[ERROR] urls[31] = file:/root/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar
maven out>[ERROR] urls[32] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0-alpha-10/doxia-module-apt-1.0-alpha-10.jar
maven out>[ERROR] urls[33] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0-alpha-10/doxia-module-fml-1.0-alpha-10.jar
maven out>[ERROR] urls[34] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0-alpha-10/doxia-module-xdoc-1.0-alpha-10.jar
maven out>[ERROR] urls[35] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0-alpha-10/doxia-module-xhtml-1.0-alpha-10.jar
maven out>[ERROR] urls[36] = file:/root/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
maven out>[ERROR] urls[37] = file:/root/.m2/repository/org/slf4j/slf4j-api/1.5.10/slf4j-api-1.5.10.jar
maven out>[ERROR] urls[38] = file:/root/.m2/repository/org/sonatype/gossip/gossip/1.2/gossip-1.2.jar
maven out>[ERROR] Number of foreign imports: 1
maven out>[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
maven out>[ERROR] 
maven out>[ERROR] -----------------------------------------------------
maven out>[ERROR] -> [Help 1]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:336)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:91)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

Could it crash there because of a failed test? I introduced a new phoneset and didn't find all files with expected test results to adjust the expected output to my phoneset...

This version was cloned from git last week.

Thanks!

**Comment by psibre** [comment] 2015-08-10 10:48
~~Way~~ *Barely* ahead of you; this is a duplicate of #375 that was fixed this morning.

**Closed by psibre** 2015-08-10 10:48 UTC
Labels: bug, duplicate, voicebuilding

**Comment by entenbein** [comment] 2015-08-10 11:35
worked like a charm!
