### ISSUE TITLE
Website demo broken in Safari Version 13.1.1 

### ISSUE THREAD

**Issue by JimKillock** [marytts/marytts#1010] opened 2020-07-01 07:03 UTC
The website demo at http://mary.dfki.de:59125 does not function in Safari 13.1.1 Mac OS, although it works fine in FF and Chrome on Mac OS.

**Comment by seblemaguer** [comment] 2020-07-01 08:57
Hello,

that is too vague. Could you be more precise?

**Comment by JimKillock** [comment] 2020-07-01 08:59
On pressing "speak", on Safari 13.1.1 Mac OS, the player reports "ERROR".

**Comment by psibre** [comment] 2020-07-02 03:47
Thanks for the the report!

Confirmed, reproducible. Will investigate.

**Comment by psibre** [comment] 2020-07-02 04:09
Turns out this is actually a duplicate of #839. Closing in favor of that one.

**Comment by psibre** [comment] 2020-07-02 04:10
As a workaround, please use Firefox or Chrome, which works without problems even on macOS Catalina.

**Closed by psibre** 2020-07-02 04:10 UTC
Labels: bug, duplicate
