### ISSUE TITLE
multiple dots -> processing time * 100

### ISSUE THREAD

**Issue by qwertologe** [marytts/marytts#590] opened 2016-09-10 21:36 UTC
Processed text:

```
6 UG und seine Objekte ........................................................................................................... 7 Toilettenanlage ...................................................................................................................... 8 Aufzug ................................................................................................................................... 9 Treppe ................................................................................................................................... 9 Führung allgemein................................................................................................................10 Homepage
```

The dots are from a table of contents - on the left side is the text. Multiple dots until the right side is reached followed by the page number.

Mary shows some problems:

`[I/O dispatcher 2] ERROR marytts.JPhonemiser_de Problem with token <.> []: Cannot syllabify empty phone string`

The message above is repeated really often (number of dots?!).

```
[I/O dispatcher 2] INFO  marytts.R 24 Next module: Prosody
[I/O dispatcher 2] INFO  marytts.R 24 Next module: PronunciationModel
[I/O dispatcher 2] INFO  marytts.R 24 Next module: AcousticModeller
[I/O dispatcher 2] INFO  marytts.R 24 Next module: Synthesis
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.Synthesis Audio format conversion required for voice dfki-pavoque-styles
[I/O dispatcher 2] INFO  marytts.R 24 Request processed in 101886 ms.
```

See processing time - this is **really** long for the text.

If i squeeze the dots (`tr -s '.'`), the text is done in a second.

**Comment by psibre** [comment] 2016-09-10 22:22
Thanks for reporting this issue! It appears to affect only German, and is triggered by the tokenizer splitting up the many dots into as many "sentences". That could be avoided by configuring JTok appropriately, but first we should update it to the [current version](/DFKI-MLT/JTok/releases/tag/v2.1.17). This however will need to come after v5.2 is released.

**Comment by qwertologe** [comment] 2016-09-11 11:04
This bug makes Mary often unusable for german language. Any chance for 5.2 or at least a 5.3 version? I don't know how early 6.0 will be released. Maybe you can provide some information for the assumed release period for the final 5.2, maybe a 5.3 and 6.0?!

Some issues which make Mary often unusable for use with german language are not fixed until 6.0: #488 (times), #488 (strange problems with some words) and now this issues.

Theses issues render Mary often unusable (stacktrace or unacceptable performance). I support a blind friend of mine. He is not able to bypass these problems.

Even the simple provided german dictionary entries in #487 have 6.0 as milestone...

Yes i know - i can use the userdict. But the problems which have 6.0 as milestone remain.

So i would be glad to hear an early date for 6.0 or hope to change your mind for some of the issues to be fixed in 5.2.

Please don't understand me wrong - i appreciate your work!

**Comment by psibre** [comment] 2016-09-12 01:18
There are so many things wrong with this, it makes my eyes bleed.

The performance hit comes from the ProsodyGeneric module. It's a spaghetti code nightmare, and inserts lots of boundaries and phrases around individual dot "tokens", which causes a crazy amount of XML processing (specifically, [DomUtils.encloseNodesWithNewElement](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-common/src/main/java/marytts/util/dom/DomUtils.java#L716-L752).

This in turn happens because [ProsodyGeneric.getBoundary](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-runtime/src/main/java/marytts/modules/ProsodyGeneric.java#L998-L1056) (which is **not a getter at all**, but modifies the XML structure!) looks at the POS tags and decides to *insert* boundaries.

The POS tags in turn are predicted by a maximum entropy model (from [OpenNLP maxent](http://maxent.sourceforge.net/about.html)), and are pretty much garbage (see also #298, #309, and #460). The dot "tokens" should be marked as punctuation, e.g., `pos="$,"`, but tend to be marked as `pos="VVINF"` or `pos="PTKZU"`. This in turn causes the tokens to be *skipped* by the [ToBI rule that's designed to prevent the insertion of boundaries](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-languages/marytts-lang-de/src/main/resources/marytts/language/de/prosody/tobipredparams_german.xml#L368-L372) after such tokens. As a consequence, the rules predict a boundary tone, and [a boundary is inserted](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-runtime/src/main/java/marytts/modules/ProsodyGeneric.java#L1028-L1038). Which causes the performance-hitting XML manipulation that seems to scale exponentially with the complexity of the document, which was originally caused by breaking up the dots in the tokenizer.

**Comment by psibre** [comment] 2016-09-12 01:21
So, one possibility of avoiding this mess for v5.2 is to ensure that a punctuation POS is assigned to the dot "tokens" before the prosody prediction. It's not a proper solution, but we want to avoid wasting time on fixing all of these fundamental issues with the tokenizer, POS tagger, prosody rules, and XML handling, when all of those things will be dropped, replaced, or upgraded for v6.0

**Comment by qwertologe** [comment] 2016-09-12 05:06
Thanks for all the explanation. I won't waste your time. I will build a workaround for the dots. This will work. You can move the milestone to 6.0 again.

It would be nice if you can have a look at #484 and #488 if there is a 5.2 milestone possible. For #484 i am not able to workaround. For #488 maybe...

**Comment by psibre** [comment] 2016-09-14 19:10
Actually, there is also a significant performance hit in the text preprocessing modules due to yet more internal XML processing. It looks like the best option is really to nip this in the bud and prevent splitting up multiple punctuation marks at the tokenization stage.

**Closed** 2016-09-14 19:32 UTC
Labels: bug

**Comment by qwertologe** [comment] 2016-09-14 19:34
@psibre you are great - thx!
