### ISSUE TITLE
en_GB_lexicon.fst

### ISSUE THREAD

**Issue by Peppemao** [marytts/marytts#307] opened 2015-04-23 08:20 UTC
I would like to know how it has been created the file en_GB_lexicon.fst and how it could be read.

**Comment by Munzey** [comment] 2015-04-23 12:32
The en_GB_lexicon.fst and en_GB.lts found in marytts master branch is actually just a duplicate of the en_US  cmudict.fst and cmudict.lts. When marytts was being actively maintained a few years ago(as it is now), the team had planned to have separate locals for each with separate pronunciation dictionaries and letter to sound rules, however that never came to fruition. 

That being said, mary may be updated with a real en_GB_lexicon.fst and en_GB.lts soon. 

If you would like to know how the current cmudict.fst and cmudict.lts was created from the cmudict-0.4.scm file found in marytts-languages/marytts-lang-en/lib/modules/en/us/lexicon/cmu/ , please refer to marytts-builder/src/main/java/marytts/tools/newlanguage/en_US/CMUDict2MaryFST.java

If you have a transcription file that is formatted in the following style: 
$word(graphemes) $phonemes $functional(optional) 
where each is seperated by whitespace, tab etc.,
you can use the LTSLexiconPOSBuilder class found in the seperate mary module: 
marytts-transcription/src/main/java/marytts/tools/transcription/LTSLexiconPOSBuilder

All mary *.fst files can be read using the FSTLookup class found in marytts-common/src/main/java/marytts/fst/

**Closed** 2015-04-23 12:33 UTC
