### ISSUE TITLE
Problem with FeatureMaker

### ISSUE THREAD

**Issue by haquynh1505** [marytts/marytts#652] opened 2016-11-30 03:59 UTC
Hello everyone,
I'm needing some help for the following problem. 
I've been trying to get supported for my language Vietnamese, running wkdb_featuremaker.sh and this one shows up

-------------------------------------------------------------------------------------------
FeatureMaker parameters:
  -locale vi
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=vi
Mysql connection created successfully.
    TABLE = "vi_dbselection" already exists, should it be deleted (y/n)?y
Checking if vi_dbselection already exist.
TABLE = vi_dbselection already exist, adding sentences to this table.
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from vi_cleanText
Number of unprocessed clean_text records to process --> [846]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:30_11_2016_09:45:58

Exception in thread "main" java.lang.NullPointerException
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:202)
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:231)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:170)

------------------------------------------------------------------------------------------

Does anybody know how to deal with it? Thanks a lot in advance!

**Comment by haquynh1505** [comment] 2016-12-02 15:21
I have been following the instructions on wiki to get New Language Support for several days (https://github.com/marytts/marytts/wiki/New-Language-Support). I have run through the first three steps successfully. Unfortunately, the fourth one does not seem to go well. I mean I tested my language project, the prompt informed that it was successful. Then I installed marytts, the prompt again informed that it was successful, and I found my language right on it.

![1](https://cloud.githubusercontent.com/assets/11997775/20839000/70c9199c-b8dd-11e6-8bb2-78d0a861bbbe.png)


But when I went check on maryserver, I could not find my language at all. 

![2](https://cloud.githubusercontent.com/assets/11997775/20839004/77718158-b8dd-11e6-992c-bd908f975c36.png)


Then I tried to check the TARGETFEATURES for my locale (vi), this one showed up. 

![3](https://cloud.githubusercontent.com/assets/11997775/20839014/7d4a952e-b8dd-11e6-9557-1675e4eb33a0.png)


From all these, I suppose that I have yet to get fully supported for my language. I have been trying the steps in the instructions again and again, but seeing no different outcome. 
I suppose that I just can not ignore this irritating error, because when I tried to run the fifth step, it showed this

![4](https://cloud.githubusercontent.com/assets/11997775/20839041/94e82e9e-b8dd-11e6-9ccd-7e1b9ecc7efe.png)


Does anybody know about this? Thanks a lot in advance! 
@psibre

**Comment by psibre** [comment] 2016-12-03 08:23
It looks like your new `marytts-lang-vi` is being built by Maven, but does not contain all things required to make it work with MaryTTS. Please go through the instruction at https://github.com/marytts/marytts/wiki/New-Language-Support#4-minimal-nlp-components-for-the-new-language very carefully.

**Comment by haquynh1505** [comment] 2016-12-05 07:53
@psibre: I think I follow the instruction quite carefully. These are my edited files: 
_ Maven project file:
[pom.txt](https://github.com/marytts/marytts/files/630366/pom.txt)
_ Sources  file from Transcription tool:
[allophones.vi.txt](https://github.com/marytts/marytts/files/630371/allophones.vi.txt)
[vi.txt](https://github.com/marytts/marytts/files/630372/vi.txt)
_ Runtime files from the transcription tool:
[allophones.vi.txt](https://github.com/marytts/marytts/files/630374/allophones.vi.txt)
[vi.txt](https://github.com/marytts/marytts/files/630376/vi.txt)
[vi_lexicon.txt](https://github.com/marytts/marytts/files/630379/vi_lexicon.txt)
[vi_pos.txt](https://github.com/marytts/marytts/files/630387/vi_pos.txt)
_ Default text for your language:
[TEXT.vi.example.txt](https://github.com/marytts/marytts/files/630403/TEXT.vi.example.txt)
_ The config file:
[vi.config.txt](https://github.com/marytts/marytts/files/630409/vi.config.txt)
_ Config loader:
[VietnameseConfig.java.txt](https://github.com/marytts/marytts/files/630414/VietnameseConfig.java.txt)
_ Refer to the new config loader:
[marytts.config.MaryConfig.txt](https://github.com/marytts/marytts/files/630425/marytts.config.MaryConfig.txt)
_ Master pom:
[pom.xml.txt](https://github.com/marytts/marytts/files/630427/pom.xml.txt)
_ Include it as a dependency in the assembly-plugin:
[pom.xml.txt](https://github.com/marytts/marytts/files/630431/pom.xml.txt)

Do I need to add anything else? 
Thank you!

**Comment by psibre** [comment] 2016-12-05 08:17
It seems you're missing the service loader. That would be your problem right there.

**Comment by haquynh1505** [comment] 2016-12-05 14:12
@psibre : sorry, it's not marytts.config.MaryConfig, is it? 
I don't see the file that you mention in other packages of other languages.

**Comment by psibre** [comment] 2016-12-05 14:25
Sorry, maybe I'm confused. The directory structure is significant, but not evident from the files you attached. You need to have your `marytts.config.MaryConfig` file in a directory named `src/main/resources/META-INF/services`. Is that the case?

**Comment by haquynh1505** [comment] 2016-12-05 14:35
@psibre : I have it in the right folder. I've been following the instruction carefully.

**Comment by nshmyrev** [comment] 2016-12-05 19:28
It is better to share your project included all the files in an archive, not as individual files.

**Comment by haquynh1505** [comment] 2016-12-06 01:52
@psibre @nshmyrev : this is my language project. Hope that you guys could figure out the problem. Thank you so much in advance! 
[marytts-lang-vi.zip](https://github.com/marytts/marytts/files/632771/marytts-lang-vi.zip)

**Comment by psibre** [comment] 2016-12-06 10:54
Here is the full stacktrace that exposes the issue:
```
Exception in thread "main" java.lang.Exception: Cannot instantiate feature processor manager 'marytts.features.FeatureProcessorManager(vi)'
	at marytts.server.Mary.setupFeatureProcessors(Mary.java:187)
	at marytts.server.Mary.startup(Mary.java:294)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.server.Mary.main(Mary.java:513)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate object from 'marytts.features.FeatureProcessorManager(vi)': Too many strings for a byte-string translator: 
"0" "0_L" "0_R" "E1_L" "E1_R" "E2_L" "E2_R" "E3_L" "E3_R" "E4_L" "E4_R" "E5_L" "E5_R" "E6_L" "E6_R" "E7_L" "E7_R" "E8_L" "E8_R" "EX1_L" "EX1_R" "EX2_L" "EX2_R" "EX3_L" "EX3_R" "EX4_L" "EX4_R" "EX5_L" "EX5_R" "EX6_L" "EX6_R" "EX7_L" "EX7_R" "EX8_L" "EX8_R" "G_L" "G_R" "J_L" "J_R" "M1_L" "M1_R" "M2_L" "M2_R" "M3_L" "M3_R" "M4_L" "M4_R" "M5_L" "M5_R" "M6_L" "M6_R" "M7_L" "M7_R" "M8_L" "M8_R" "MW1_L" "MW1_R" "MW2_L" "MW2_R" "MW3_L" "MW3_R" "MW4_L" "MW4_R" "MW5_L" "MW5_R" "MW6_L" "MW6_R" "MW7_L" "MW7_R" "MW8_L" "MW8_R" "N_L" "N_R" "N1_L" "N1_R" "N2_L" "N2_R" "N3_L" "N3_R" "N4_L" "N4_R" "N5_L" "N5_R" "N6_L" "N6_R" "Nm1_L" "Nm1_R" "Nm2_L" "Nm2_R" "Nm3_L" "Nm3_R" "Nm4_L" "Nm4_R" "Nm5_L" "Nm5_R" "Nm6_L" "Nm6_R" "Nn1_L" "Nn1_R" "Nn2_L" "Nn2_R" "Nn3_L" "Nn3_R" "Nn4_L" "Nn4_R" "Nn5_L" "Nn5_R" "Nn6_L" "Nn6_R" "O1_L" "O1_R" "O2_L" "O2_R" "O3_L" "O3_R" "O4_L" "O4_R" "O5_L" "O5_R" "O6_L" "O6_R" "O7_L" "O7_R" "O8_L" "O8_R" "OX1_L" "OX1_R" "OX2_L" "OX2_R" "OX3_L" "OX3_R" "OX4_L" "OX4_R" "OX5_L" "OX5_R" "OX6_L" "OX6_R" "OX7_L" "OX7_R" "OX8_L" "OX8_R" "W1_L" "W1_R" "W2_L" "W2_R" "W3_L" "W3_R" "W4_L" "W4_R" "W5_L" "W5_R" "W6_L" "W6_R" "W7_L" "W7_R" "W8_L" "W8_R" "WX1_L" "WX1_R" "WX2_L" "WX2_R" "WX3_L" "WX3_R" "WX4_L" "WX4_R" "WX5_L" "WX5_R" "WX6_L" "WX6_R" "WX7_L" "WX7_R" "WX8_L" "WX8_R" "__L" "__R" "a1_L" "a1_R" "a2_L" "a2_R" "a3_L" "a3_R" "a4_L" "a4_R" "a5_L" "a5_R" "a6_L" "a6_R" "a7_L" "a7_R" "a8_L" "a8_R" "aX1_L" "aX1_R" "aX2_L" "aX2_R" "aX3_L" "aX3_R" "aX4_L" "aX4_R" "aX5_L" "aX5_R" "aX6_L" "aX6_R" "aX7_L" "aX7_R" "aX8_L" "aX8_R" "b_L" "b_R" "ch_L" "ch_R" "d_L" "d_R" "e1_L" "e1_R" "e2_L" "e2_R" "e3_L" "e3_R" "e4_L" "e4_R" "e5_L" "e5_R" "e6_L" "e6_R" "e7_L" "e7_R" "e8_L" "e8_R" "f_L" "f_R" "h_L" "h_R" "i1_L" "i1_R" "i2_L" "i2_R" "i3_L" "i3_R" "i4_L" "i4_R" "i5_L" "i5_R" "i6_L" "i6_R" "i7_L" "i7_R" "i8_L" "i8_R" "ie1_L" "ie1_R" "ie2_L" "ie2_R" "ie3_L" "ie3_R" "ie4_L" "ie4_R" "ie5_L" "ie5_R" "ie6_L" "ie6_R" "ie7_L" "ie7_R" "ie8_L" "ie8_R" "j1_L" "j1_R" "j2_L" "j2_R" "j3_L" "j3_R" "j4_L" "j4_R" "j5_L" "j5_R" "j6_L" "j6_R" "k_L" "k_R" "k7_L" "k7_R" "k8_L" "k8_R" "kc7_L" "kc7_R" "kc8_L" "kc8_R" "kp7_L" "kp7_R" "kp8_L" "kp8_R" "l_L" "l_R" "m_L" "m_R" "m1_L" "m1_R" "m2_L" "m2_R" "m3_L" "m3_R" "m4_L" "m4_R" "m5_L" "m5_R" "m6_L" "m6_R" "n_L" "n_R" "n1_L" "n1_R" "n2_L" "n2_R" "n3_L" "n3_R" "n4_L" "n4_R" "n5_L" "n5_R" "n6_L" "n6_R" "o1_L" "o1_R" "o2_L" "o2_R" "o3_L" "o3_R" "o4_L" "o4_R" "o5_L" "o5_R" "o6_L" "o6_R" "o7_L" "o7_R" "o8_L" "o8_R" "p_L" "p_R" "p7_L" "p7_R" "p8_L" "p8_R" "s_L" "s_R" "t_L" "t_R" "t7_L" "t7_R" "t8_L" "t8_R" "th_L" "th_R" "u1_L" "u1_R" "u2_L" "u2_R" "u3_L" "u3_R" "u4_L" "u4_R" "u5_L" "u5_R" "u6_L" "u6_R" "u7_L" "u7_R" "u8_L" "u8_R" "uo1_L" "uo1_R" "uo2_L" "uo2_R" "uo3_L" "uo3_R" "uo4_L" "uo4_R" "uo5_L" "uo5_R" "uo6_L" "uo6_R" "uo7_L" "uo7_R" "uo8_L" "uo8_R" "v_L" "v_R" "w1_L" "w1_R" "w2_L" "w2_R" "w3_L" "w3_R" "w4_L" "w4_R" "w5_L" "w5_R" "w6_L" "w6_R" "w7_L" "w7_R" "w8_L" "w8_R" "x_L" "x_R" "z_L" "z_R" (407 strings)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:130)
	at marytts.server.Mary.setupFeatureProcessors(Mary.java:178)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:124)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Too many strings for a byte-string translator: 
"0" "0_L" "0_R" "E1_L" "E1_R" "E2_L" "E2_R" "E3_L" "E3_R" "E4_L" "E4_R" "E5_L" "E5_R" "E6_L" "E6_R" "E7_L" "E7_R" "E8_L" "E8_R" "EX1_L" "EX1_R" "EX2_L" "EX2_R" "EX3_L" "EX3_R" "EX4_L" "EX4_R" "EX5_L" "EX5_R" "EX6_L" "EX6_R" "EX7_L" "EX7_R" "EX8_L" "EX8_R" "G_L" "G_R" "J_L" "J_R" "M1_L" "M1_R" "M2_L" "M2_R" "M3_L" "M3_R" "M4_L" "M4_R" "M5_L" "M5_R" "M6_L" "M6_R" "M7_L" "M7_R" "M8_L" "M8_R" "MW1_L" "MW1_R" "MW2_L" "MW2_R" "MW3_L" "MW3_R" "MW4_L" "MW4_R" "MW5_L" "MW5_R" "MW6_L" "MW6_R" "MW7_L" "MW7_R" "MW8_L" "MW8_R" "N_L" "N_R" "N1_L" "N1_R" "N2_L" "N2_R" "N3_L" "N3_R" "N4_L" "N4_R" "N5_L" "N5_R" "N6_L" "N6_R" "Nm1_L" "Nm1_R" "Nm2_L" "Nm2_R" "Nm3_L" "Nm3_R" "Nm4_L" "Nm4_R" "Nm5_L" "Nm5_R" "Nm6_L" "Nm6_R" "Nn1_L" "Nn1_R" "Nn2_L" "Nn2_R" "Nn3_L" "Nn3_R" "Nn4_L" "Nn4_R" "Nn5_L" "Nn5_R" "Nn6_L" "Nn6_R" "O1_L" "O1_R" "O2_L" "O2_R" "O3_L" "O3_R" "O4_L" "O4_R" "O5_L" "O5_R" "O6_L" "O6_R" "O7_L" "O7_R" "O8_L" "O8_R" "OX1_L" "OX1_R" "OX2_L" "OX2_R" "OX3_L" "OX3_R" "OX4_L" "OX4_R" "OX5_L" "OX5_R" "OX6_L" "OX6_R" "OX7_L" "OX7_R" "OX8_L" "OX8_R" "W1_L" "W1_R" "W2_L" "W2_R" "W3_L" "W3_R" "W4_L" "W4_R" "W5_L" "W5_R" "W6_L" "W6_R" "W7_L" "W7_R" "W8_L" "W8_R" "WX1_L" "WX1_R" "WX2_L" "WX2_R" "WX3_L" "WX3_R" "WX4_L" "WX4_R" "WX5_L" "WX5_R" "WX6_L" "WX6_R" "WX7_L" "WX7_R" "WX8_L" "WX8_R" "__L" "__R" "a1_L" "a1_R" "a2_L" "a2_R" "a3_L" "a3_R" "a4_L" "a4_R" "a5_L" "a5_R" "a6_L" "a6_R" "a7_L" "a7_R" "a8_L" "a8_R" "aX1_L" "aX1_R" "aX2_L" "aX2_R" "aX3_L" "aX3_R" "aX4_L" "aX4_R" "aX5_L" "aX5_R" "aX6_L" "aX6_R" "aX7_L" "aX7_R" "aX8_L" "aX8_R" "b_L" "b_R" "ch_L" "ch_R" "d_L" "d_R" "e1_L" "e1_R" "e2_L" "e2_R" "e3_L" "e3_R" "e4_L" "e4_R" "e5_L" "e5_R" "e6_L" "e6_R" "e7_L" "e7_R" "e8_L" "e8_R" "f_L" "f_R" "h_L" "h_R" "i1_L" "i1_R" "i2_L" "i2_R" "i3_L" "i3_R" "i4_L" "i4_R" "i5_L" "i5_R" "i6_L" "i6_R" "i7_L" "i7_R" "i8_L" "i8_R" "ie1_L" "ie1_R" "ie2_L" "ie2_R" "ie3_L" "ie3_R" "ie4_L" "ie4_R" "ie5_L" "ie5_R" "ie6_L" "ie6_R" "ie7_L" "ie7_R" "ie8_L" "ie8_R" "j1_L" "j1_R" "j2_L" "j2_R" "j3_L" "j3_R" "j4_L" "j4_R" "j5_L" "j5_R" "j6_L" "j6_R" "k_L" "k_R" "k7_L" "k7_R" "k8_L" "k8_R" "kc7_L" "kc7_R" "kc8_L" "kc8_R" "kp7_L" "kp7_R" "kp8_L" "kp8_R" "l_L" "l_R" "m_L" "m_R" "m1_L" "m1_R" "m2_L" "m2_R" "m3_L" "m3_R" "m4_L" "m4_R" "m5_L" "m5_R" "m6_L" "m6_R" "n_L" "n_R" "n1_L" "n1_R" "n2_L" "n2_R" "n3_L" "n3_R" "n4_L" "n4_R" "n5_L" "n5_R" "n6_L" "n6_R" "o1_L" "o1_R" "o2_L" "o2_R" "o3_L" "o3_R" "o4_L" "o4_R" "o5_L" "o5_R" "o6_L" "o6_R" "o7_L" "o7_R" "o8_L" "o8_R" "p_L" "p_R" "p7_L" "p7_R" "p8_L" "p8_R" "s_L" "s_R" "t_L" "t_R" "t7_L" "t7_R" "t8_L" "t8_R" "th_L" "th_R" "u1_L" "u1_R" "u2_L" "u2_R" "u3_L" "u3_R" "u4_L" "u4_R" "u5_L" "u5_R" "u6_L" "u6_R" "u7_L" "u7_R" "u8_L" "u8_R" "uo1_L" "uo1_R" "uo2_L" "uo2_R" "uo3_L" "uo3_R" "uo4_L" "uo4_R" "uo5_L" "uo5_R" "uo6_L" "uo6_R" "uo7_L" "uo7_R" "uo8_L" "uo8_R" "v_L" "v_R" "w1_L" "w1_R" "w2_L" "w2_R" "w3_L" "w3_R" "w4_L" "w4_R" "w5_L" "w5_R" "w6_L" "w6_R" "w7_L" "w7_R" "w8_L" "w8_R" "x_L" "x_R" "z_L" "z_R" (407 strings)
	at marytts.util.string.ByteStringTranslator.<init>(ByteStringTranslator.java:81)
	at marytts.features.MaryLanguageFeatureProcessors$HalfPhoneUnitName.<init>(MaryLanguageFeatureProcessors.java:140)
	at marytts.features.FeatureProcessorManager.setupPhoneFeatureProcessors(FeatureProcessorManager.java:308)
	at marytts.features.FeatureProcessorManager.<init>(FeatureProcessorManager.java:52)
	at marytts.features.FeatureProcessorManager.<init>(FeatureProcessorManager.java:44)
	... 9 more
```

**Comment by psibre** [comment] 2016-12-06 10:56
@haquynh1505 Thanks for providing all the details.

As we discover, this issue is pretty much a duplicate of #73.

**Comment by nshmyrev** [comment] 2016-12-06 15:25
You can probably redesign your phoneset to use less phones, you can use just tone height instead of tone id for nucleus and coda as described in https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/icassp2004_chao.pdf. You also need to add tone feature to vowel so it can be used in modeling.

Also discussed at https://github.com/marytts/marytts/issues/620

**Comment by haquynh1505** [comment] 2016-12-07 02:33
@psibre @nshmyrev : Thank you guys for your help! I will firstly try to redesign my phoneset. Hope that it would not effect the quality of the synthesized voice

**Comment by nshmyrev** [comment] 2016-12-07 12:58
@haquynh1505 actually smaller phoneset usually means better quality since you learn from data, not restrict manually. You can see that in the paper above too.

**Comment by haquynh1505** [comment] 2016-12-15 10:43
@psibre @nshmyrev : hi guys, I've been working on this issue for few days, trying to redesign my phoneset. Unfortunately, I have yet to come with any reasonable solutions. All the efforts to reduce the number of phones result in a smaller number, but it's still quite big. This again produces the same issue I suppose. 
I think I need to try changing the source code. Do you guy have any suggestion that where I should start going? Thanks a lot!

**Comment by nshmyrev** [comment] 2016-12-21 22:50
@haquynh1505, you need to look inside FeatureProcessorManager.java and MaryLanguageFeatureProcessors.java, its going to be a significant change.

I suggest you to revisit phoneset size, you can share your current effort to get help.

**Comment by haquynh1505** [comment] 2016-12-29 03:59
@psibre @nshmyrev : Hi guys, I am wondering how could you threw these exceptions? I am building mary on Ubuntu using command line. I had not seen these before that why I could not notice the errors.

**Comment by MomnaSaeed** [comment] 2017-01-11 20:34
Hi , Searching for solution  to my error  , i found that your exception in feature maker is kind of similar to mine as i am also getting an exception in database selection command while working on New language support for Urdu. 
The particular issue is posted here 
https://github.com/marytts/marytts/issues/672
also the feature maker command retrieves 0 sentences in ur_PK_dbselection" table.
https://github.com/marytts/marytts/issues/674
These two links have details of the problem i am facing.
I want to ask if you have resolved your exception ,what steps you took to sort it out ,please share some suggestion.
Thank you

**Comment by haquynh1505** [comment] 2017-01-12 02:06
Hi,

I am so sorry but I have yet to fix it. I've been changing something in the
code and it turns out that it's a massive change.

**Closed** 2020-04-14 12:30 UTC
Labels: duplicate, newlanguage
