### ISSUE TITLE
BUG: Simple phonemes to audio

### ISSUE THREAD

**Issue by kingjr** [marytts/marytts#464] opened 2016-01-29 17:12 UTC
Running the default example of `INPUT_TYPE=SIMPLEPHONEMES` (`vIl-'kO_m@n ?In d6 'vElt d6 'SpRa:x-zYn-,te:-z@`) to `OUTPUT_TYPE=AUDIO` fails to make audio.

The [server report the following error](http://mary.dfki.de:59125/process?INPUT_TYPE=SIMPLEPHONEMES&OUTPUT_TYPE=AUDIO&INPUT_TEXT=vIl-%27kO_m%40n%20%3FIn%20d6%20%27vElt%20d6%20%27SpRa%3Ax-zYn-%2Cte%3A-z%40%0A&OUTPUT_TEXT=&effect_Volume_selected=&effect_Volume_parameters=amount%3A2.0%3B&effect_Volume_default=Default&effect_Volume_help=Help&effect_TractScaler_selected=&effect_TractScaler_parameters=amount%3A1.5%3B&effect_TractScaler_default=Default&effect_TractScaler_help=Help&effect_F0Scale_selected=&effect_F0Scale_parameters=f0Scale%3A2.0%3B&effect_F0Scale_default=Default&effect_F0Scale_help=Help&effect_F0Add_selected=&effect_F0Add_parameters=f0Add%3A50.0%3B&effect_F0Add_default=Default&effect_F0Add_help=Help&effect_Rate_selected=&effect_Rate_parameters=durScale%3A1.5%3B&effect_Rate_default=Default&effect_Rate_help=Help&effect_Robot_selected=&effect_Robot_parameters=amount%3A100.0%3B&effect_Robot_default=Default&effect_Robot_help=Help&effect_Whisper_selected=&effect_Whisper_parameters=amount%3A100.0%3B&effect_Whisper_default=Default&effect_Whisper_help=Help&effect_Stadium_selected=&effect_Stadium_parameters=amount%3A100.0&effect_Stadium_default=Default&effect_Stadium_help=Help&effect_Chorus_selected=&effect_Chorus_parameters=delay1%3A466%3Bamp1%3A0.54%3Bdelay2%3A600%3Bamp2%3A-0.10%3Bdelay3%3A250%3Bamp3%3A0.30&effect_Chorus_default=Default&effect_Chorus_help=Help&effect_FIRFilter_selected=&effect_FIRFilter_parameters=type%3A3%3Bfc1%3A500.0%3Bfc2%3A2000.0&effect_FIRFilter_default=Default&effect_FIRFilter_help=Help&effect_JetPilot_selected=&effect_JetPilot_parameters=&effect_JetPilot_default=Default&effect_JetPilot_help=Help&HELP_TEXT=&exampleTexts=&VOICE_SELECTIONS=bits3%20de%20male%20unitselection%20general&AUDIO_OUT=WAVE_FILE&LOCALE=de&VOICE=bits3&AUDIO=WAVE_FILE):
```
Internal server error

Processing failed.

java.lang.AssertionError: Unexpected tag name: expected syllable, got t
	at marytts.features.MaryGenericFeatureProcessors$SyllableNavigator.getElement(MaryGenericFeatureProcessors.java:271)
	at marytts.features.MaryGenericFeatureProcessors$Accented.process(MaryGenericFeatureProcessors.java:725)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:137)
	at marytts.unitselection.select.FFRTargetCostFunction.computeTargetFeatures(FFRTargetCostFunction.java:298)
	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.computeTargetFeatures(DiphoneFFRTargetCostFunction.java:133)
	at marytts.unitselection.select.UnitSelector.selectUnits(UnitSelector.java:110)
	at marytts.unitselection.UnitSelectionSynthesizer.synthesize(UnitSelectionSynthesizer.java:169)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:501)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:263)
	at marytts.modules.Synthesis.process(Synthesis.java:232)
	at marytts.server.Request.processOneChunk(Request.java:549)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
	at marytts.server.Request.process(Request.java:298)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by attacomsian** [comment] 2016-02-01 13:26
This issue will be fixed along https://github.com/marytts/marytts/issues/280

You can also find the work around in comments.

**Comment by kingjr** [comment] 2016-02-01 14:06
Great thanks

**Comment by psibre** [comment] 2016-02-25 14:26
I can't reproduce this any more... seems fixed.

**Closed by psibre** 2016-02-25 14:26 UTC
Labels: bug, invalid

**Comment by psibre** [comment] 2016-02-25 14:28
For the record, this was a duplicate of #467

**Comment by kingjr** [comment] 2016-02-25 14:30
I would say it's the contrary ;)

**Comment by psibre** [comment] 2016-02-25 15:59
@kingjr right, but the other issue was already fixed... =)
