### ISSUE TITLE
Feature Maker Extraction Problem

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#538] opened 2016-05-27 06:38 UTC
Hello, I am trying to add support for the Hindi Language and i am in the 5th step. While running the Feature Maker I found the following error. Can somebody please guide me through this as it is very urgent.

```
matarani@matarani-Lenovo-G580:/media/matarani/01CEB84761F97410/marytts-master-new/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_featuremaker.sh wkdb.conf
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

FeatureMaker parameters:
  -locale hn
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB hindidb
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=hn
Mysql connection created successfully.
    TABLE = "hn_dbselection" already exists, should it be deleted (y/n)?y
Checking if hn_dbselection already exist.
TABLE = hn_dbselection already exist, adding sentences to this table.
Starting builtin MARY TTS...v
I
l
k
O
m
@
n
?
I
n
d
6
v
E
l
t
d
6
S
p
R
a:
x
z
Y
n
t
e:
z
@
w
E
l
k
@
m
t
@
D
@
w
r=
l
d
@
v
s
p
i
tS
s
I
n
T
@
s
I
s
 MARY TTS started.

Getting list of unprocessed clean_text records from hn_cleanText
Number of unprocessed clean_text records to process --> [5845]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:27_05_2016_12:03:53


Created featureDefinition file:hn_featureDefinition.txt
Processing(0) text id=5935 text length=8561
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=5935
```

Thank You.

**Comment by BibekBazaz** [comment] 2016-05-27 06:39
@psibre @sathishpc @ftesser @giuliopaci   Please help.

**Comment by seblemaguer** [comment] 2016-05-27 08:59
the maryserver doesn't find the proper module sequence to generate the phoneme. I suspect that your module use to produce the phoneme is not in the classpath

**Comment by BibekBazaz** [comment] 2016-06-01 17:23
Can you please tell me how to fix this in steps. I have tried without any success to solve the probem. I need  help urgently. Please.

**Comment by giuliopaci** [comment] 2016-06-01 20:09
Hi, my guess is the same as @seblemaguer, but it is very hard to say without having access to your setup. Are sources available?

**Comment by psibre** [comment] 2016-06-01 20:46
Have a look at [our Hindi module](/marytts/marytts-lang-hi), which is not in great shape, but should show you how to fix your module problem.

**Comment by BibekBazaz** [comment] 2016-06-06 06:51
Hello Everyone, thanks for your valuable suggestions. I corrected the error. In my allophoneset.hn.xml file, I mistakenly used locale as hi_IN where as my locale is hn. That was creating the error. Once I corrected that I have been able to run featuremaker and dbselection steps and after recording voices have reached the VoiceBuilding step. But when I run the PraatPitchMarker it shows an out of memory error though I have 400GB available space. Please provide your guidance as to how to overcome this error.

**Comment by BibekBazaz** [comment] 2016-06-06 06:52
The error is as follows:


matarani@matarani-Lenovo-G580:/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$ ./voiceimport.sh 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Loading database layout:
Reading config file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/database.config
Loading basename list from file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst
Found 6 files in basename list
Computing pitchmarks for 6 utterances.
Running Praat as: praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500
Error: Out of memory: there is not enough room for 2147483647 more elements whose sizes are 8 bytes each.
Matrix of elements not created.
Sound not created.
Sound not read from sound file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav//s1.wav”.
Script line 66 not performed or completed:
« wav = Read from file... 'wavFile$' »
Script “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat” not completed.
Praat: command file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500” not completed.

java.lang.Exception: The component PraatPitchmarker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: PraatPitchmarker computation failed on file []!
Command line was: [praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500].
	at marytts.util.io.General.launchProc(General.java:549)
	at marytts.tools.voiceimport.PraatPitchmarker.compute(PraatPitchmarker.java:294)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
matarani@matarani-Lenovo-G580:/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$

**Comment by BibekBazaz** [comment] 2016-06-08 05:57
@psibre Please look into my current issue and help me with your guidance.

**Comment by psibre** [comment] 2016-06-08 06:01
@BibekBazaz If this issue is solved, please close it. You previous message indicates you may be affected by #540.

**Comment by psibre** [comment] 2016-06-08 06:03
@BibekBazaz On second thought, it might be something else, but nevertheless, please open a new issue for your memory error.

**Comment by giuliopaci** [comment] 2016-06-08 06:20
@psibre, @BibekBazaz: this does not seem a memory error to me, but a signed error code interpreted as an unsigned number of elements. I have not read the relevant code, but I guess there is an error there.

The real error seems to be:

`Caused by: java.lang.RuntimeException: PraatPitchmarker computation failed on file []!`

That seems to indicate an empty file is used somewhere, probably leading to the error code above. Is there an empty line at `/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst`? Does that file have carriage returns?

**Comment by BibekBazaz** [comment] 2016-06-08 07:17
@giuliopaci The error is in praat. The file [ ] is actually the location of the pm directory that mary creates. But it contains nothing.
The out of memory error is because of the sampling size. I tried to reduce it in praat gui but it does not get reduced. The sound objects in praat are long sound objects. I tried to create the matrix manually but I have no idea what the elements of the matrix should be. There is no details about the matrix in marytts documentation in github. 
The basename.lst does not contain any empty lines but the names of the sound files in serial order.

**Comment by giuliopaci** [comment] 2016-06-08 07:40
@BibekBazaz: I just wanted to point out this is likely not an out of memory issue (2^31-1 samples seem stramge to me). Did you check #540 as @psibre suggested?

**Comment by psibre** [comment] 2016-06-08 07:48
@BibekBazaz I'm having trouble understanding your problem, and the discussion seems to have moved from the original issue (which you say above is solved) to something entirely different. Please clean out your voicebuilding directory to make sure your data is not corrupted, and if you encounter problems after that, open a new issue.

**Closed by psibre** 2016-06-08 07:48 UTC
