### ISSUE TITLE
error in praat

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#736] opened 2017-04-29 19:21 UTC
i have found some issue in praat while trying to rebuild my voice , earlier i run the praat command manually to generate the point process files
because of manually running the command the praat goes green because the pointprocess and pm files are generated thats why i proceeded before.
![image](https://cloud.githubusercontent.com/assets/9119099/25558251/22f32040-2d3c-11e7-8fce-3dd2dc16054e.png)
 but i think that didn't worked properly so caused the problem of no audio after building , i got this error in praat 
 
![image](https://cloud.githubusercontent.com/assets/9119099/25558164/38e6d02e-2d3a-11e7-971b-e860f793f663.png)
while this is praat script
![image](https://cloud.githubusercontent.com/assets/9119099/25558168/4cd7629c-2d3a-11e7-9304-fa9f6fbfa756.png)

[script_praat.txt](https://github.com/marytts/marytts/files/966348/script_praat.txt)
This is the setting i did for a female voice 
![image](https://cloud.githubusercontent.com/assets/9119099/25558192/e1294730-2d3a-11e7-8272-467ad03de4f1.png)

(uploading script.praat in txt format because praat is not supported here)
![image](https://cloud.githubusercontent.com/assets/9119099/25558214/5a861072-2d3b-11e7-9801-f6b28a67ff29.png)
![image](https://cloud.githubusercontent.com/assets/9119099/25558218/7e518fd6-2d3b-11e7-848c-2a1a20fed885.png)

it says no audio data even though wav files are present in wav folder
![image](https://cloud.githubusercontent.com/assets/9119099/25558220/90c26e10-2d3b-11e7-9b8b-da438a5440fa.png)
![image](https://cloud.githubusercontent.com/assets/9119099/25558221/98c63808-2d3b-11e7-8e67-7422ad03196a.png)
these are all the errors i get from praat
please suggest something to fix this praat error 

thank you

**Comment by psibre** [comment] 2017-04-30 06:40
I think this is probably a duplicate of #540. Please see if [my comment](../issues/540#issuecomment-224472064) there solves the issue.

**Closed** 2017-05-03 22:13 UTC
Labels: voicebuilding
