### ISSUE TITLE
Execution failed for task ':marytts-languages:marytts-lang-it:test'.

### ISSUE THREAD

**Issue by elnursamedzade** [marytts/marytts#991] opened 2020-05-20 12:23 UTC
God ... like a nightmare. I'm getting an error again.

```
19 tests completed, 3 failed, 3 skipped

> Task :marytts-languages:marytts-lang-it:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':marytts-languages:marytts-lang-it:test'.
> There were failing tests. See the report at: file:///C:/Users/Elnur/marytts/marytts-languages/marytts-lang-it/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU¦LD FAILED in 2m 45s
155 actionable tasks: 155 executed
```

Here is the index.html output in the C:\Users\Elnur\marytts\marytts-languages\marytts-lang-it\build\reports\tests\test directory:

```
Test Summary
19
tests
3
failures
3
ignored
0.305s
duration
81%
successful
Failed tests
Ignored tests
Packages
Classes
ItalianConfigExtraTest. canGet
ItalianConfigExtraTest. hasItalianLocale
ItalianConfigTest. setup
Generated by Gradle 6.3 at 20.May.2020 16:00:40

```

The page that opens when I click on the setup:
```
Class marytts.language.it.ItalianConfigTest
all > marytts.language.it > ItalianConfigTest
4
tests
1
failures
3
ignored
0.005s
duration
0%
successful
Failed tests
Tests
 
setup
marytts.exceptions.MaryConfigurationException: cannot load properties
	at marytts.config.MaryConfig.<init>(MaryConfig.java:197)
	at marytts.config.LanguageConfig.<init>(LanguageConfig.java:42)
	at marytts.language.it.ItalianConfig.<init>(ItalianConfig.groovy:8)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:241)
	at marytts.language.it.ItalianConfigTest.setup(ItalianConfigTest.groovy:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:510)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at java.util.Scanner.<init>(Scanner.java:563)
	at marytts.util.io.PropertiesTrimTrailingWhitespace.load(PropertiesTrimTrailingWhitespace.java:21)
	at marytts.config.MaryConfig.<init>(MaryConfig.java:195)
	... 69 more
Wrap lines
Generated by Gradle 6.3 at 20.May.2020 16:00:40

```

**Comment by seblemaguer** [comment] 2020-05-20 13:02
It doesn't find `italian.config`. I don't have this problem on my side and I don't manage to reproduce it. Could indicate:
  1. what is the command you used?
  2. what did you modify in this your repository?

**Comment by elnursamedzade** [comment] 2020-05-20 14:21
1. The command I use is gradlew build
2. I have not changed anything in this repo. I just cloned and gave the
command above.

Sébastien Le Maguer <notifications@github.com>, 20 May 2020 Çar, 17:03
tarihinde şunu yazdı:

**Comment by seblemaguer** [comment] 2020-05-20 18:12
Ok thanks. It seems that a lot of issues appear on windows that I can't reproduce on my side. I will focus on updating the CI to support windows to be able to test more easily and I come back to you.

**Comment by elnursamedzade** [comment] 2020-05-20 18:41
OK. I will look forward to you. Good work!

Sébastien Le Maguer <notifications@github.com>, 20 May 2020 Çar, 22:12
tarihinde şunu yazdı:

**Comment by psibre** [comment] 2020-05-21 09:44
At the current master
```
marytts$ git describe 
v5.2-347-g713ffad9a
```
I get no errors at all on a vanilla Windows 10 VM:
```
﻿C:\vagrant\marytts>gradlew build
[...]
﻿BUILD SUCCESSFUL in 6m 57s
203 actionable tasks: 203 executed
```
I have
```
﻿C:\vagrant\marytts>gradlew --version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Oracle Corporation 25.252-b09)
OS:           Windows 10 10.0 amd64
```
@elnursamedzade Which Java version are you running?

**Comment by seblemaguer** [comment] 2020-05-21 10:16
to complete, the PR #992 shows that for all openjdk from 1.8, 1.11, 1.12 on linux, windows and macos, everything is working fine

**Comment by elnursamedzade** [comment] 2020-05-21 21:44
Hello, Mr Psibre and Sébastien.
java version I use in my windows:
java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

C:\Users\Elnur\marytts>gradlew -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
OS:           Windows 10 10.0 amd64


The ubuntu terminal output I installed on Windows:
java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)


elka@DESKTOP-LCA50BE:~/marytts$ ./gradlew -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.4.0-18362-Microsoft amd64

Currently the build  with the ubuntu terminal is successful. This is enough
for me.
elka@DESKTOP-LCA50BE:~$ cd marytts
elka@DESKTOP-LCA50BE:~/marytts$ ./gradlew build

BUILD SUCCESSFUL in 3s
203 actionable tasks: 203 up-to-date

I think the error I got on Windows is related to the java version. I'll fix
this in the future.
Right now, I would like you to take a look at the issue that makes me think.
https://github.com/marytts/voice-dfki-ot/issues/3
Thanks.

**Comment by seblemaguer** [comment] 2020-05-24 11:12
To have a proper formatting, here was the previous message:

Hello, Mr Psibre and Sébastien.

```
java version I use in my windows:
java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

C:\Users\Elnur\marytts>gradlew -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
OS:           Windows 10 10.0 amd64

```

The ubuntu terminal output I installed on Windows:

```
java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)


elka@DESKTOP-LCA50BE:~/marytts$ ./gradlew -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.4.0-18362-Microsoft amd64
```

Currently the build  with the ubuntu terminal is successful. This is enough
for me.
```
elka@DESKTOP-LCA50BE:~$ cd marytts
elka@DESKTOP-LCA50BE:~/marytts$ ./gradlew build

BUILD SUCCESSFUL in 3s
203 actionable tasks: 203 up-to-date
```

I think the error I got on Windows is related to the java version. I'll fix
this in the future.
Right now, I would like you to take a look at the issue that makes me think.
https://github.com/marytts/voice-dfki-ot/issues/3
Thanks.

**Comment by psibre** [comment] 2020-05-28 04:54
@elnursamedzade Could you please report the Java version that led to the error you reported under Windows? Because if this is a bug, we would like to fix it.

**Comment by elnursamedzade** [comment] 2020-05-28 05:50
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by psibre** [comment] 2020-05-28 05:58
Right, sorry! I just realized that you had already provided this information!

OK, this is strange, because for me under Windows 10 with Java 8, I cannot reproduce this error at all. I'll close this for now, but we will try to test more thoroughly under Windows when we have time.

**Closed by psibre** 2020-05-28 05:58 UTC
Labels: worksforme
