### ISSUE TITLE
"ur_PK_dbselection" table is empty

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#674] opened 2017-01-10 21:14 UTC
![image](https://cloud.githubusercontent.com/assets/9119099/21824794/cf723eae-d7a2-11e6-9f83-9a366aff0229.png)
![image](https://cloud.githubusercontent.com/assets/9119099/21824818/e67e11fe-d7a2-11e6-86f6-b5c96a2c164e.png)
 I am working on TTS for urdu language , the issue i am entangled is in the step 5 and 6 of new language support. 
https://github.com/marytts/marytts/wiki/New-Language-Support
This command  "$ ./wkdb_database_selector.sh /home/student/wiki/wkdb.conf" creates "ur_PK_dbselection" table but it is empty which raises an exception in next step.
please suggest me a something to resolve this problem .
Thank you.

**Comment by seblemaguer** [comment] 2017-01-12 07:10
duplicate of #652 so I suggest the discussion continues on this thread. I close this one

**Closed by seblemaguer** 2017-01-12 07:10 UTC

**Comment by MomnaSaeed** [comment] 2017-01-12 09:25
The comments on problem#652 didn't solved my issue ,so i want this issue#674 opened. Also if you have any idea about how to sort this out ,please let me know.
Thank you.
