### ISSUE TITLE
weird issue with locale en_US and the string "abaf"

### ISSUE THREAD

**Issue by pepperpepperpepper** [marytts/marytts#297] opened 2015-03-31 00:25 UTC
so when I query the mary server as so:
curl 'http://localhost:59125/process'  --data 'INPUT_TYPE=TEXT&OUTPUT_TYPE=ALLOPHONES&INPUT_TEXT=abaft&AUDIO_OUT=WAVE_FILE&LOCALE=en_US'

I get a 500 error, it only happens with the en_US locale...seems like a typo somewhere?

**Comment by psibre** [comment] 2015-03-31 08:36
While I would expect this to be a duplicate of several open bugs about the ongoing refit of the English lexicon, this particular one I can't reproduce. Could you please provide a stacktrace from the server?

**Comment by pepperpepperpepper** [comment] 2015-03-31 23:47
java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:549)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: en_US)
	at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
	at marytts.modules.phonemiser.Syllabifier.correctStressSymbol(Syllabifier.java:297)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:252)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:52)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:166)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:225)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:153)
	at marytts.server.Request.processOneChunk(Request.java:547)

**Comment by psibre** [comment] 2015-05-05 12:25
This is actually a duplicate of #285. We're pushing out a fix soon.

**Closed by psibre** 2015-05-05 12:25 UTC
Labels: bug

**Comment by quakig** [comment] 2015-05-14 19:04
I am getting a similar message when trying to use 'AllophonesExtractor' script . I cloned the github code around 5 days back and build it using maven.

    Caused by: java.lang.IllegalArgumentException: Allophone `'' could not be found in AllophoneSet `sampa' (Locale: en_US)

Here's the complete stack trace:

```java
Computing ALLOPHONES files for 7 files
Mary TTS client 5.2-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2-SNAPSHOT (impl. unknown)
java.lang.Exception: The component AllophonesExtractor produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Allophone `'' could not be found in AllophoneSet `sampa' (Locale: en_US)
	at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:550)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:236)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:164)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 19 more
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
	at marytts.client.MaryClient.process(MaryClient.java:653)
	at marytts.client.MaryClient.process(MaryClient.java:659)
	at marytts.tools.voiceimport.AllophonesExtractor.generateAllophonesFile(AllophonesExtractor.java:218)
	at marytts.tools.voiceimport.AllophonesExtractor.compute(AllophonesExtractor.java:150)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:388)
	... 6 more
```

**Comment by Munzey** [comment] 2015-05-15 15:01
we still havent merged the fix yet into master, will be soon. we will close issue #285 when it is
