### ISSUE TITLE
getting exception during conversion of a Turkish text

### ISSUE THREAD

**Issue by kommradHomer** [marytts/marytts#415] opened 2015-10-06 13:20 UTC
getting an exception while trying to process this text

```
"onur kendigelen 2, B, H, R, S, 16, 53, 30, 09, 71, 8 , SENSÖRÜ"

2015-10-01 09:24:15,488 [I/O dispatcher 4] INFO  marytts.R 11084 New request (input type "TEXT", output type "AUDIO", voice "dfki-ot-hsmm", effect "FIRFilter(type:3;fc1:200.0;fc2:16000.0)", audio "WAVE")
2015-10-01 09:24:15,488 [I/O dispatcher 4] INFO  marytts.server Read: onur kendigelen iki B, H, R, S, on alt? elli ?? otuz  dokuz yetmi? bir sekiz , SENS?R?
2015-10-01 09:24:15,488 [I/O dispatcher 4] INFO  marytts.R 11084 Handling request using the following modules:
2015-10-01 09:24:15,488 [I/O dispatcher 4] INFO  marytts.R 11084 - TextToMaryXML (marytts.modules.TextToMaryXML)
2015-10-01 09:24:15,488 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: TextToMaryXML
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 Handling request using the following modules:
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - JTokeniser (marytts.modules.JTokeniser)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - DummyTokens2Words (marytts.modules.DummyTokens2Words)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - OpenNLPPosTagger (marytts.modules.MinimalisticPosTagger)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - JPhonemiser (marytts.modules.JPhonemiser)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - Prosody (marytts.modules.ProsodyGeneric)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - PronunciationModel (marytts.modules.PronunciationModel)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - AcousticModeller (marytts.modules.AcousticModeller)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 - Synthesis (marytts.modules.Synthesis)
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: JTokeniser
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: DummyTokens2Words
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: OpenNLPPosTagger
2015-10-01 09:24:15,489 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: JPhonemiser
2015-10-01 09:24:15,491 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: Prosody
2015-10-01 09:24:15,492 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: PronunciationModel
2015-10-01 09:24:15,493 [I/O dispatcher 4] INFO  marytts.R 11084 Next module: AcousticModeller
2015-10-01 09:24:15,503 [I/O dispatcher 4] INFO  marytts.ParameterGeneration Parameter generation for LF0:
2015-10-01 09:24:15,503 [I/O dispatcher 4] INFO  marytts.PStream Global variance optimization
2015-10-01 09:24:15,505 [I/O dispatcher 4] INFO  marytts.PStream Gradient GV optimization for feature: (0)  number of iterations=23
2015-10-01 09:24:15,506 [I/O dispatcher 4] ERROR marytts.server Processing failed.
java.lang.Exception: Module AcousticModeller: Problem processing the data.
    at marytts.server.Request.processOneChunk(Request.java:551)
    at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
    at marytts.server.Request.process(Request.java:336)
    at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
    at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
    at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
    at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
    at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
    at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at marytts.util.math.MathUtils.interpolateNonZeroValues(MathUtils.java:5004)
    at marytts.modules.acoustic.ProsodyElementHandler.getF0Contour(ProsodyElementHandler.java:470)
    at marytts.modules.acoustic.ProsodyElementHandler.getF0Contour(ProsodyElementHandler.java:396)
    at marytts.modules.acoustic.ProsodyElementHandler.process(ProsodyElementHandler.java:96)
    at marytts.modules.AcousticModeller.process(AcousticModeller.java:254)
    at marytts.server.Request.processOneChunk(Request.java:549)
    ... 19 more
2015-10-01 09:24:15,507 [I/O dispatcher 4] INFO  marytts.server Request couldn't be handled successfully.
2015-10-01 09:24:31,609 [I/O dispatcher 4] INFO  marytts.server Connection closed: [closed]
```

**Comment by psibre** [comment] 2015-10-06 18:47
I cannot reproduce this.

### `TEXT`
```
onur kendigelen 2, B, H, R, S, 16, 53, 30, 09, 71, 8 , SENSÖRÜ
```

### `ALLOPHONES`
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="tr">
<p>
<s>
<prosody pitch="+5%" range="+20%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="o - ' n u r" pos="content">
onur
<syllable ph="o">
<ph d="110" end="0.11" f0="(6,134)(13,133)(20,131)(26,131)(33,131)(40,132)(46,132)(53,133)(60,133)(66,133)(73,134)(80,134)(86,135)(93,135)(100,131)" p="o"/>
</syllable>
<syllable accent="L+H*" ph="n u r" stress="1">
<ph d="60" end="0.17" f0="(8,131)(16,129)(25,129)(33,128)(41,128)(50,127)(58,127)(66,127)(75,127)(83,128)(91,128)(100,130)" p="n"/>
<ph d="75" end="0.245" f0="(6,130)(13,129)(20,129)(26,131)(33,131)(40,133)(46,133)(53,135)(60,135)(66,137)(73,137)(80,135)(86,135)(93,135)(100,133)" p="u"/>
<ph d="35" end="0.28" f0="(50,131)(100,110)" p="r"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="rules" ph="k e n - d I - g e - ' l e n" pos="content">
kendigelen
<syllable ph="k e n">
<ph d="110" end="0.39" p="k"/>
<ph d="130" end="0.52" f0="(3,120)(7,118)(11,118)(15,116)(19,116)(23,114)(26,114)(30,113)(34,113)(38,112)(42,112)(46,111)(50,111)(53,111)(57,110)(61,110)(65,110)(69,110)(73,109)(76,109)(80,108)(84,108)(88,107)(92,107)(96,105)(100,105)" p="e"/>
<ph d="75" end="0.59499997" f0="(6,105)(13,105)(20,106)(26,106)(33,106)(40,106)(46,106)(53,106)(60,106)(66,106)(73,106)(80,106)(86,106)(93,106)(100,106)" p="n"/>
</syllable>
<syllable ph="d I">
<ph d="35" end="0.63" f0="(14,105)(28,105)(42,104)(57,104)(71,108)(85,108)(100,106)" p="d"/>
<ph d="45" end="0.675" f0="(11,106)(22,105)(33,105)(44,104)(55,104)(66,103)(77,103)(88,99)(100,99)" p="I"/>
</syllable>
<syllable ph="g e">
<ph d="65" end="0.74" f0="(7,98)(15,98)(23,97)(30,97)(38,97)(46,99)(53,99)(61,103)(69,103)(76,106)(84,106)(92,107)(100,107)" p="g"/>
<ph d="70" end="0.81" f0="(7,104)(14,104)(21,102)(28,102)(35,101)(42,101)(50,101)(57,101)(64,101)(71,101)(78,99)(85,99)(92,98)(100,98)" p="e"/>
</syllable>
<syllable accent="L+H*" ph="l e n" stress="1">
<ph d="55" end="0.865" f0="(9,99)(18,99)(27,99)(36,99)(45,99)(54,99)(63,99)(72,100)(81,100)(90,102)(100,102)" p="l"/>
<ph d="105" end="0.97" f0="(4,99)(9,99)(14,98)(19,98)(23,98)(28,98)(33,98)(38,98)(42,99)(47,99)(52,101)(57,101)(61,101)(66,102)(71,102)(76,102)(80,102)(85,101)(90,101)(95,101)(100,101)" p="e"/>
<ph d="85" end="1.0550001" f0="(5,106)(11,106)(17,107)(23,107)(29,105)(35,105)(41,104)(47,104)(52,103)(58,103)(64,102)(70,102)(76,100)(82,100)(88,100)(94,100)(100,100)" p="n"/>
</syllable>
</t>
<t pos="content">
2
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+4%" range="+16%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' b" pos="content">
B
<syllable accent="L+H*" ph="b" stress="1">
<ph d="115" end="1.1700001" f0="(4,109)(9,109)(14,108)(19,107)(23,107)(28,108)(33,109)(38,110)(42,110)(47,111)(52,110)(57,109)(61,109)(66,108)(71,107)(76,107)(80,107)(85,106)(90,106)(95,106)(100,106)" p="b"/>
</syllable>
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+3%" range="+12%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' h" pos="content">
H
<syllable accent="L+H*" ph="h" stress="1">
<ph d="190" end="1.3600001" p="h"/>
</syllable>
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+2%" range="+9%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' r" pos="content">
R
<syllable accent="L+H*" ph="r" stress="1">
<ph d="245" end="1.6050001" f0="(4,109)(8,110)(12,110)(16,110)(20,111)(24,111)(28,111)(32,111)(36,111)(40,112)(44,112)(48,113)(52,129)(56,130)(60,130)(64,130)(68,131)(72,131)(76,131)(80,132)(84,132)(88,132)(92,132)(96,133)(100,133)" p="r"/>
</syllable>
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+1%" range="+5%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' s" pos="content">
S
<syllable accent="L+H*" ph="s" stress="1">
<ph d="190" end="1.7950001" p="s"/>
</syllable>
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+0%" range="+1%">
<phrase>
<t pos="content">
16
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="+0%" range="-1%">
<phrase>
<t pos="content">
53
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-1%" range="-5%">
<phrase>
<t pos="content">
30
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-2%" range="-9%">
<phrase>
<t pos="content">
09
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-3%" range="-12%">
<phrase>
<t pos="content">
71
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-4%" range="-16%">
<phrase>
<t pos="content">
8
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" duration="400" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-5%" range="-20%">
<phrase>
<t accent="!H*" g2p_method="rules" ph="' s e n - s @' r Z" pos="content">
SENSÖRÜ
<syllable accent="!H*" ph="s e n" stress="1">
<ph d="135" end="1.9300001" p="s"/>
<ph d="100" end="2.03" f0="(5,110)(10,106)(15,98)(20,98)(25,98)(30,97)(35,97)(40,97)(45,96)(50,95)(55,95)(60,95)(65,94)(70,94)(75,93)(80,93)(85,91)(90,91)(95,90)(100,89)" p="e"/>
<ph d="35" end="2.065" f0="(14,89)(28,90)(42,90)(57,91)(71,91)(85,90)(100,89)" p="n"/>
</syllable>
<syllable ph="s @' r Z">
<ph d="110" end="2.175" p="s"/>
<ph d="85" end="2.26" f0="(6,79)(13,80)(20,82)(26,82)(33,84)(40,86)(46,89)(53,89)(60,89)(66,89)(73,89)(80,88)(86,83)(93,83)(100,82)" p="@'"/>
<ph d="60" end="2.32" f0="(11,81)(22,82)(33,84)(44,85)(55,86)(66,87)(77,88)(88,77)(100,78)" p="r"/>
<ph d="190" end="2.51" f0="(3,78)(7,77)(11,76)(15,75)(19,75)(23,75)(26,75)(30,74)(34,74)(38,74)(42,74)(46,73)(50,73)(53,73)(57,73)(61,73)(65,73)(69,72)(73,72)(76,72)(80,72)(84,71)(88,71)(92,70)(96,70)(100,70)" p="Z"/>
</syllable>
</t>
<boundary breakindex="5" duration="400" tone="L-L%"/>
</phrase>
</prosody>
</s>
</p>
</maryxml>
```
### `AUDIO`
[process.mp3.txt](https://github.com/marytts/marytts/files/8756/process.mp3.txt)
(remove `.txt` suffix added to avoid GitHub limitation)

**Comment by psibre** [comment] 2015-10-07 08:25
I'm confused by your stacktrace -- the line number in MathUtils makes no sense to me.
1. Which version of MaryTTS are you using?
2. Is this a duplicate of #237?

**Comment by seblemaguer** [comment] 2015-10-20 11:41
@kommradHomer Did you manage to solve your problem ?

**Comment by seblemaguer** [comment] 2015-10-30 08:08
I close this issue as we can't reproduce it and it seems to be solved on your side

**Closed by seblemaguer** 2015-10-30 08:08 UTC
